/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1.0.0-alpha.8
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-alpha.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ListDevicesResponse,
    ListDevicesResponseFromJSON,
    ListDevicesResponseToJSON,
} from '../models/ListDevicesResponse';
import {
    type ProblemDetails,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/ProblemDetails';

/**
 * 
 */
export class AudioApiService extends runtime.BaseAPI {

    /**
     * Creates request options for listAudioDevices without sending the request
     */
    async listAudioDevicesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/audio/devices`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Enumerates all available audio input devices on the host system.  **Use Case:** Call this endpoint when configuring audio streaming settings to present the user with a list of audio devices to choose from.  **Device Information:** - **Index**: Device identifier used to select the device for capture - **Name**: Human-readable device name for display in UI - **MaxInputChannels**: Number of audio channels the device supports - **DefaultSampleRate**: The device\'s preferred sample rate  Returns an empty list if no audio input devices are available.
     * List Audio Input Devices
     */
    async listAudioDevicesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListDevicesResponse>> {
        const requestOptions = await this.listAudioDevicesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListDevicesResponseFromJSON(jsonValue));
    }

    /**
     * Enumerates all available audio input devices on the host system.  **Use Case:** Call this endpoint when configuring audio streaming settings to present the user with a list of audio devices to choose from.  **Device Information:** - **Index**: Device identifier used to select the device for capture - **Name**: Human-readable device name for display in UI - **MaxInputChannels**: Number of audio channels the device supports - **DefaultSampleRate**: The device\'s preferred sample rate  Returns an empty list if no audio input devices are available.
     * List Audio Input Devices
     */
    async listAudioDevices(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListDevicesResponse> {
        const response = await this.listAudioDevicesRaw(initOverrides);
        return await response.value();
    }

}
