/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1.0.0-alpha.8
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-alpha.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type FindDevicesResponse,
    FindDevicesResponseFromJSON,
    FindDevicesResponseToJSON,
} from '../models/FindDevicesResponse';
import {
    type PingDeviceResponse,
    PingDeviceResponseFromJSON,
    PingDeviceResponseToJSON,
} from '../models/PingDeviceResponse';
import {
    type ProblemDetails,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/ProblemDetails';
import {
    type ResetDeviceResponse,
    ResetDeviceResponseFromJSON,
    ResetDeviceResponseToJSON,
} from '../models/ResetDeviceResponse';
import {
    type StartLogsResponse,
    StartLogsResponseFromJSON,
    StartLogsResponseToJSON,
} from '../models/StartLogsResponse';
import {
    type StopLogsResponse,
    StopLogsResponseFromJSON,
    StopLogsResponseToJSON,
} from '../models/StopLogsResponse';

export interface FindDevicesRequest {
    fullScan: boolean;
}

export interface PingDeviceRequest {
    deviceId: string;
}

export interface ResetDeviceRequest {
    deviceId: string;
}

/**
 * 
 */
export class DevicesApiService extends runtime.BaseAPI {

    /**
     * Creates request options for findDevices without sending the request
     */
    async findDevicesRequestOpts(requestParameters: FindDevicesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['fullScan'] == null) {
            throw new runtime.RequiredError(
                'fullScan',
                'Required parameter "fullScan" was null or undefined when calling findDevices().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['fullScan'] != null) {
            queryParameters['FullScan'] = requestParameters['fullScan'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/devices`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns all available and connected TeensyROM devices.  - This will momentarily disconnect all devices. - All available COM ports will be scanned for TeensyROM devices. - TCP devices use cached IPs by default (fullScan=false) for fast discovery. - Set fullScan=true to perform a complete network scan for TCP devices. - Devices with auto-connect enabled will reconnect automatically.
     * Find Devices
     */
    async findDevicesRaw(requestParameters: FindDevicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FindDevicesResponse>> {
        const requestOptions = await this.findDevicesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FindDevicesResponseFromJSON(jsonValue));
    }

    /**
     * Returns all available and connected TeensyROM devices.  - This will momentarily disconnect all devices. - All available COM ports will be scanned for TeensyROM devices. - TCP devices use cached IPs by default (fullScan=false) for fast discovery. - Set fullScan=true to perform a complete network scan for TCP devices. - Devices with auto-connect enabled will reconnect automatically.
     * Find Devices
     */
    async findDevices(requestParameters: FindDevicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FindDevicesResponse> {
        const response = await this.findDevicesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for pingDevice without sending the request
     */
    async pingDeviceRequestOpts(requestParameters: PingDeviceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['deviceId'] == null) {
            throw new runtime.RequiredError(
                'deviceId',
                'Required parameter "deviceId" was null or undefined when calling pingDevice().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/devices/{deviceId}/ping`;
        urlPath = urlPath.replace('{deviceId}', encodeURIComponent(String(requestParameters['deviceId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Pings a TeensyROM device to check if it is responsive.  - Works the same as clicking the cartridge reset button.
     * Ping Device
     */
    async pingDeviceRaw(requestParameters: PingDeviceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PingDeviceResponse>> {
        const requestOptions = await this.pingDeviceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PingDeviceResponseFromJSON(jsonValue));
    }

    /**
     * Pings a TeensyROM device to check if it is responsive.  - Works the same as clicking the cartridge reset button.
     * Ping Device
     */
    async pingDevice(requestParameters: PingDeviceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PingDeviceResponse> {
        const response = await this.pingDeviceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for resetDevice without sending the request
     */
    async resetDeviceRequestOpts(requestParameters: ResetDeviceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['deviceId'] == null) {
            throw new runtime.RequiredError(
                'deviceId',
                'Required parameter "deviceId" was null or undefined when calling resetDevice().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/devices/{deviceId}/reset`;
        urlPath = urlPath.replace('{deviceId}', encodeURIComponent(String(requestParameters['deviceId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Resets a TeensyROM device.  - Works the same as clicking the cartridge reset button.
     * Reset Device
     */
    async resetDeviceRaw(requestParameters: ResetDeviceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResetDeviceResponse>> {
        const requestOptions = await this.resetDeviceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResetDeviceResponseFromJSON(jsonValue));
    }

    /**
     * Resets a TeensyROM device.  - Works the same as clicking the cartridge reset button.
     * Reset Device
     */
    async resetDevice(requestParameters: ResetDeviceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResetDeviceResponse> {
        const response = await this.resetDeviceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for startLogs without sending the request
     */
    async startLogsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/logs`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Starts the logging service and returns a success message.
     * Start Logging Hub
     */
    async startLogsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StartLogsResponse>> {
        const requestOptions = await this.startLogsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StartLogsResponseFromJSON(jsonValue));
    }

    /**
     * Starts the logging service and returns a success message.
     * Start Logging Hub
     */
    async startLogs(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StartLogsResponse> {
        const response = await this.startLogsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for stopLogs without sending the request
     */
    async stopLogsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/logs`;

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Stops the logging service and returns a success message.
     * Stop Logging Channel
     */
    async stopLogsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StopLogsResponse>> {
        const requestOptions = await this.stopLogsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StopLogsResponseFromJSON(jsonValue));
    }

    /**
     * Stops the logging service and returns a success message.
     * Stop Logging Channel
     */
    async stopLogs(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StopLogsResponse> {
        const response = await this.stopLogsRaw(initOverrides);
        return await response.value();
    }

}
