/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1.0.0-alpha.8
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-alpha.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type GetDirectoryResponse,
    GetDirectoryResponseFromJSON,
    GetDirectoryResponseToJSON,
} from '../models/GetDirectoryResponse';
import {
    type IndexAllResponse,
    IndexAllResponseFromJSON,
    IndexAllResponseToJSON,
} from '../models/IndexAllResponse';
import {
    type IndexResponse,
    IndexResponseFromJSON,
    IndexResponseToJSON,
} from '../models/IndexResponse';
import {
    type NullableOfTeensyFilterType,
    NullableOfTeensyFilterTypeFromJSON,
    NullableOfTeensyFilterTypeToJSON,
} from '../models/NullableOfTeensyFilterType';
import {
    type ProblemDetails,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/ProblemDetails';
import {
    type RemoveFavoriteResponse,
    RemoveFavoriteResponseFromJSON,
    RemoveFavoriteResponseToJSON,
} from '../models/RemoveFavoriteResponse';
import {
    type SaveFavoriteResponse,
    SaveFavoriteResponseFromJSON,
    SaveFavoriteResponseToJSON,
} from '../models/SaveFavoriteResponse';
import {
    type SearchResponse,
    SearchResponseFromJSON,
    SearchResponseToJSON,
} from '../models/SearchResponse';
import {
    type TeensyStorageType,
    TeensyStorageTypeFromJSON,
    TeensyStorageTypeToJSON,
} from '../models/TeensyStorageType';

export interface GetDirectoryRequest {
    deviceId: string;
    storageType: TeensyStorageType;
    path?: string;
}

export interface IndexRequest {
    deviceId: string;
    storageType: TeensyStorageType;
    startingPath?: string;
}

export interface RemoveFavoriteRequest {
    deviceId: string;
    storageType: TeensyStorageType;
    filePath: string;
}

export interface SaveFavoriteRequest {
    deviceId: string;
    storageType: TeensyStorageType;
    filePath: string;
}

export interface SearchRequest {
    deviceId: string;
    searchText: string;
    skip: number;
    take: number;
    filterType?: NullableOfTeensyFilterType;
}

/**
 * 
 */
export class FilesApiService extends runtime.BaseAPI {

    /**
     * Creates request options for getDirectory without sending the request
     */
    async getDirectoryRequestOpts(requestParameters: GetDirectoryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['deviceId'] == null) {
            throw new runtime.RequiredError(
                'deviceId',
                'Required parameter "deviceId" was null or undefined when calling getDirectory().'
            );
        }

        if (requestParameters['storageType'] == null) {
            throw new runtime.RequiredError(
                'storageType',
                'Required parameter "storageType" was null or undefined when calling getDirectory().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['path'] != null) {
            queryParameters['Path'] = requestParameters['path'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/devices/{deviceId}/storage/{storageType}/directories`;
        urlPath = urlPath.replace('{deviceId}', encodeURIComponent(String(requestParameters['deviceId'])));
        urlPath = urlPath.replace('{storageType}', encodeURIComponent(String(requestParameters['storageType'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets a directory for given storage device.  - Returns metadata for all files in the directory. - This is not recursive and will only include the files for the requested directory. - Make another request to get subdirectory content.
     * Get Directory
     */
    async getDirectoryRaw(requestParameters: GetDirectoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetDirectoryResponse>> {
        const requestOptions = await this.getDirectoryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetDirectoryResponseFromJSON(jsonValue));
    }

    /**
     * Gets a directory for given storage device.  - Returns metadata for all files in the directory. - This is not recursive and will only include the files for the requested directory. - Make another request to get subdirectory content.
     * Get Directory
     */
    async getDirectory(requestParameters: GetDirectoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetDirectoryResponse> {
        const response = await this.getDirectoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for index without sending the request
     */
    async indexRequestOpts(requestParameters: IndexRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['deviceId'] == null) {
            throw new runtime.RequiredError(
                'deviceId',
                'Required parameter "deviceId" was null or undefined when calling index().'
            );
        }

        if (requestParameters['storageType'] == null) {
            throw new runtime.RequiredError(
                'storageType',
                'Required parameter "storageType" was null or undefined when calling index().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['startingPath'] != null) {
            queryParameters['StartingPath'] = requestParameters['startingPath'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/devices/{deviceId}/storage/{storageType}/index`;
        urlPath = urlPath.replace('{deviceId}', encodeURIComponent(String(requestParameters['deviceId'])));
        urlPath = urlPath.replace('{storageType}', encodeURIComponent(String(requestParameters['storageType'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Indexes the directory structure of a given TeensyROM device and storage type.  - Providing a path will index starting at that directory and all subdirectories below it. - Providing no path will index the whole storage device. - Don\'t touch your commodore while indexing is in progress.
     * Index
     */
    async indexRaw(requestParameters: IndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IndexResponse>> {
        const requestOptions = await this.indexRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IndexResponseFromJSON(jsonValue));
    }

    /**
     * Indexes the directory structure of a given TeensyROM device and storage type.  - Providing a path will index starting at that directory and all subdirectories below it. - Providing no path will index the whole storage device. - Don\'t touch your commodore while indexing is in progress.
     * Index
     */
    async index(requestParameters: IndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IndexResponse> {
        const response = await this.indexRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for indexAll without sending the request
     */
    async indexAllRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/files/index/all`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Indexes all storage for all connected TeensyROM devices.  - This will recursively index all storage devices. - Multiple devices will be indexed in parallel, one device type at a time. - This could take a few minutes if you have a lot of data. - Don\'t touch your commodores while indexing is in progress.
     * Index All
     */
    async indexAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IndexAllResponse>> {
        const requestOptions = await this.indexAllRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IndexAllResponseFromJSON(jsonValue));
    }

    /**
     * Indexes all storage for all connected TeensyROM devices.  - This will recursively index all storage devices. - Multiple devices will be indexed in parallel, one device type at a time. - This could take a few minutes if you have a lot of data. - Don\'t touch your commodores while indexing is in progress.
     * Index All
     */
    async indexAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IndexAllResponse> {
        const response = await this.indexAllRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for removeFavorite without sending the request
     */
    async removeFavoriteRequestOpts(requestParameters: RemoveFavoriteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['deviceId'] == null) {
            throw new runtime.RequiredError(
                'deviceId',
                'Required parameter "deviceId" was null or undefined when calling removeFavorite().'
            );
        }

        if (requestParameters['storageType'] == null) {
            throw new runtime.RequiredError(
                'storageType',
                'Required parameter "storageType" was null or undefined when calling removeFavorite().'
            );
        }

        if (requestParameters['filePath'] == null) {
            throw new runtime.RequiredError(
                'filePath',
                'Required parameter "filePath" was null or undefined when calling removeFavorite().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['filePath'] != null) {
            queryParameters['FilePath'] = requestParameters['filePath'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/devices/{deviceId}/storage/{storageType}/favorite`;
        urlPath = urlPath.replace('{deviceId}', encodeURIComponent(String(requestParameters['deviceId'])));
        urlPath = urlPath.replace('{storageType}', encodeURIComponent(String(requestParameters['storageType'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Removes a file from favorites, deleting the favorite copy and updating the original file\'s favorite status.
     * Remove Favorite
     */
    async removeFavoriteRaw(requestParameters: RemoveFavoriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RemoveFavoriteResponse>> {
        const requestOptions = await this.removeFavoriteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RemoveFavoriteResponseFromJSON(jsonValue));
    }

    /**
     * Removes a file from favorites, deleting the favorite copy and updating the original file\'s favorite status.
     * Remove Favorite
     */
    async removeFavorite(requestParameters: RemoveFavoriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RemoveFavoriteResponse> {
        const response = await this.removeFavoriteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for saveFavorite without sending the request
     */
    async saveFavoriteRequestOpts(requestParameters: SaveFavoriteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['deviceId'] == null) {
            throw new runtime.RequiredError(
                'deviceId',
                'Required parameter "deviceId" was null or undefined when calling saveFavorite().'
            );
        }

        if (requestParameters['storageType'] == null) {
            throw new runtime.RequiredError(
                'storageType',
                'Required parameter "storageType" was null or undefined when calling saveFavorite().'
            );
        }

        if (requestParameters['filePath'] == null) {
            throw new runtime.RequiredError(
                'filePath',
                'Required parameter "filePath" was null or undefined when calling saveFavorite().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['filePath'] != null) {
            queryParameters['FilePath'] = requestParameters['filePath'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/devices/{deviceId}/storage/{storageType}/favorite`;
        urlPath = urlPath.replace('{deviceId}', encodeURIComponent(String(requestParameters['deviceId'])));
        urlPath = urlPath.replace('{storageType}', encodeURIComponent(String(requestParameters['storageType'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Saves a file as a favorite, creating a copy in the appropriate favorites directory.
     * Save Favorite
     */
    async saveFavoriteRaw(requestParameters: SaveFavoriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SaveFavoriteResponse>> {
        const requestOptions = await this.saveFavoriteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SaveFavoriteResponseFromJSON(jsonValue));
    }

    /**
     * Saves a file as a favorite, creating a copy in the appropriate favorites directory.
     * Save Favorite
     */
    async saveFavorite(requestParameters: SaveFavoriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SaveFavoriteResponse> {
        const response = await this.saveFavoriteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for search without sending the request
     */
    async searchRequestOpts(requestParameters: SearchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['deviceId'] == null) {
            throw new runtime.RequiredError(
                'deviceId',
                'Required parameter "deviceId" was null or undefined when calling search().'
            );
        }

        if (requestParameters['searchText'] == null) {
            throw new runtime.RequiredError(
                'searchText',
                'Required parameter "searchText" was null or undefined when calling search().'
            );
        }

        if (requestParameters['skip'] == null) {
            throw new runtime.RequiredError(
                'skip',
                'Required parameter "skip" was null or undefined when calling search().'
            );
        }

        if (requestParameters['take'] == null) {
            throw new runtime.RequiredError(
                'take',
                'Required parameter "take" was null or undefined when calling search().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['searchText'] != null) {
            queryParameters['SearchText'] = requestParameters['searchText'];
        }

        if (requestParameters['filterType'] != null) {
            queryParameters['FilterType'] = requestParameters['filterType'];
        }

        if (requestParameters['skip'] != null) {
            queryParameters['Skip'] = requestParameters['skip'];
        }

        if (requestParameters['take'] != null) {
            queryParameters['Take'] = requestParameters['take'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/devices/{deviceId}/search`;
        urlPath = urlPath.replace('{deviceId}', encodeURIComponent(String(requestParameters['deviceId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Searches for files across all available storage devices (SD and USB) based on search text and filter criteria.  - Searches through file names, titles, creators, and descriptions. - Returns metadata for all matching files from all available storages. - Supports file type filtering (All, Games, Music, Images, Hex). - Supports pagination with Skip and Take parameters. - Excludes favorites and playlist directories from search results. - Uses weighted search algorithm to rank results by relevance. - Default page size is 50, maximum is 200.
     * Search Files
     */
    async searchRaw(requestParameters: SearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchResponse>> {
        const requestOptions = await this.searchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchResponseFromJSON(jsonValue));
    }

    /**
     * Searches for files across all available storage devices (SD and USB) based on search text and filter criteria.  - Searches through file names, titles, creators, and descriptions. - Returns metadata for all matching files from all available storages. - Supports file type filtering (All, Games, Music, Images, Hex). - Supports pagination with Skip and Take parameters. - Excludes favorites and playlist directories from search results. - Uses weighted search algorithm to rank results by relevance. - Default page size is 50, maximum is 200.
     * Search Files
     */
    async search(requestParameters: SearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchResponse> {
        const response = await this.searchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
