/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1.0.0-alpha.8
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-alpha.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetSettingsResponse,
  HttpValidationProblemDetails,
  ProblemDetails,
  SaveSettingsRequest,
  SaveSettingsResponse,
} from '../models/index';
import {
    GetSettingsResponseFromJSON,
    GetSettingsResponseToJSON,
    HttpValidationProblemDetailsFromJSON,
    HttpValidationProblemDetailsToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    SaveSettingsRequestFromJSON,
    SaveSettingsRequestToJSON,
    SaveSettingsResponseFromJSON,
    SaveSettingsResponseToJSON,
} from '../models/index';

export interface SaveSettingsOperationRequest {
    saveSettingsRequest: SaveSettingsRequest;
}

/**
 * 
 */
export class SettingsApiService extends runtime.BaseAPI {

    /**
     * Retrieves all current user settings for the TeensyROM application.  **Settings Categories:** - **Connection Settings**: Device connectivity preferences (Serial/TCP) - **Player Settings**: Playback behavior and startup preferences - **File Transfer Settings**: Auto-copy and directory watching configuration - **Search Settings**: Search weights, stop words, and content exclusions - **App Settings**: Application lifecycle state  Settings are loaded from the Settings.json file and cached in memory. This endpoint always returns the current in-memory settings state.
     * Get User Settings
     */
    async getSettingsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetSettingsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/settings`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetSettingsResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves all current user settings for the TeensyROM application.  **Settings Categories:** - **Connection Settings**: Device connectivity preferences (Serial/TCP) - **Player Settings**: Playback behavior and startup preferences - **File Transfer Settings**: Auto-copy and directory watching configuration - **Search Settings**: Search weights, stop words, and content exclusions - **App Settings**: Application lifecycle state  Settings are loaded from the Settings.json file and cached in memory. This endpoint always returns the current in-memory settings state.
     * Get User Settings
     */
    async getSettings(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetSettingsResponse> {
        const response = await this.getSettingsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Saves all user settings for the TeensyROM application to persistent storage.  **Settings Categories:** - **Connection Settings**: Device connectivity preferences (Serial/TCP)   - Serial: Port name (empty for auto-detect) and baud rate (typically 115200)   - TCP: Host address, port (1-65535), and timeout values (milliseconds) - **Player Settings**: Playback behavior and startup preferences   - Repeat mode, play timer, mute settings, startup filter and launch options - **File Transfer Settings**: Auto-copy and directory watching configuration   - Watch directory location, auto-transfer path, and sync flags - **Search Settings**: Search weights, stop words, and content exclusions   - Search weights must be >= 0 with at least one > 0   - Stop words, banned directories, and banned files lists - **App Settings**: Application lifecycle state   - First-time setup flag  **Validation:** - All nested settings objects are required - Baud rate must be positive (typically 9600, 19200, 38400, 57600, or 115200) - TCP port must be between 1 and 65535 - Timeout values must be positive integers (milliseconds) - Watch directory must be empty or a valid absolute path - Search weights must be non-negative with at least one > 0  Settings are persisted to Settings.json and immediately available in memory.
     * Save User Settings
     */
    async saveSettingsRaw(requestParameters: SaveSettingsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SaveSettingsResponse>> {
        if (requestParameters['saveSettingsRequest'] == null) {
            throw new runtime.RequiredError(
                'saveSettingsRequest',
                'Required parameter "saveSettingsRequest" was null or undefined when calling saveSettings().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/settings`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SaveSettingsRequestToJSON(requestParameters['saveSettingsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SaveSettingsResponseFromJSON(jsonValue));
    }

    /**
     * Saves all user settings for the TeensyROM application to persistent storage.  **Settings Categories:** - **Connection Settings**: Device connectivity preferences (Serial/TCP)   - Serial: Port name (empty for auto-detect) and baud rate (typically 115200)   - TCP: Host address, port (1-65535), and timeout values (milliseconds) - **Player Settings**: Playback behavior and startup preferences   - Repeat mode, play timer, mute settings, startup filter and launch options - **File Transfer Settings**: Auto-copy and directory watching configuration   - Watch directory location, auto-transfer path, and sync flags - **Search Settings**: Search weights, stop words, and content exclusions   - Search weights must be >= 0 with at least one > 0   - Stop words, banned directories, and banned files lists - **App Settings**: Application lifecycle state   - First-time setup flag  **Validation:** - All nested settings objects are required - Baud rate must be positive (typically 9600, 19200, 38400, 57600, or 115200) - TCP port must be between 1 and 65535 - Timeout values must be positive integers (milliseconds) - Watch directory must be empty or a valid absolute path - Search weights must be non-negative with at least one > 0  Settings are persisted to Settings.json and immediately available in memory.
     * Save User Settings
     */
    async saveSettings(requestParameters: SaveSettingsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SaveSettingsResponse> {
        const response = await this.saveSettingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
