/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1.0.0-alpha.8
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-alpha.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CancelJobResponse,
    CancelJobResponseFromJSON,
    CancelJobResponseToJSON,
} from '../models/CancelJobResponse';
import {
    type CreateJobBody,
    CreateJobBodyFromJSON,
    CreateJobBodyToJSON,
} from '../models/CreateJobBody';
import {
    type CreateJobResponse,
    CreateJobResponseFromJSON,
    CreateJobResponseToJSON,
} from '../models/CreateJobResponse';
import {
    type GetActiveJobResponse,
    GetActiveJobResponseFromJSON,
    GetActiveJobResponseToJSON,
} from '../models/GetActiveJobResponse';
import {
    type GetJobResponse,
    GetJobResponseFromJSON,
    GetJobResponseToJSON,
} from '../models/GetJobResponse';
import {
    type ProblemDetails,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/ProblemDetails';
import {
    type SealJobResponse,
    SealJobResponseFromJSON,
    SealJobResponseToJSON,
} from '../models/SealJobResponse';
import {
    type TeensyStorageType,
    TeensyStorageTypeFromJSON,
    TeensyStorageTypeToJSON,
} from '../models/TeensyStorageType';
import {
    type UploadFileResponse,
    UploadFileResponseFromJSON,
    UploadFileResponseToJSON,
} from '../models/UploadFileResponse';

export interface CancelTransferJobRequest {
    jobId: string;
}

export interface CreateTransferJobRequest {
    deviceId: string;
    storageType: TeensyStorageType;
    createJobBody: CreateJobBody;
}

export interface GetActiveTransferJobRequest {
    deviceId: string;
}

export interface GetTransferJobRequest {
    jobId: string;
}

export interface SealTransferJobRequest {
    jobId: string;
}

export interface UploadTransferFileRequest {
    jobId: string;
    path: string;
}

/**
 * 
 */
export class TransfersApiService extends runtime.BaseAPI {

    /**
     * Creates request options for cancelTransferJob without sending the request
     */
    async cancelTransferJobRequestOpts(requestParameters: CancelTransferJobRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling cancelTransferJob().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/transfers/{jobId}/cancel`;
        urlPath = urlPath.replace('{jobId}', encodeURIComponent(String(requestParameters['jobId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Requests cancellation of a transfer job.  - Returns immediately - it does not wait for the drain. The pump finishes any in-flight write and drains the rest of the queue in the background. - Idempotent: cancelling an already-cancelling or already-cancelled job returns success, as does cancelling any other terminal job, without changing anything.
     * Cancel Transfer Job
     */
    async cancelTransferJobRaw(requestParameters: CancelTransferJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CancelJobResponse>> {
        const requestOptions = await this.cancelTransferJobRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CancelJobResponseFromJSON(jsonValue));
    }

    /**
     * Requests cancellation of a transfer job.  - Returns immediately - it does not wait for the drain. The pump finishes any in-flight write and drains the rest of the queue in the background. - Idempotent: cancelling an already-cancelling or already-cancelled job returns success, as does cancelling any other terminal job, without changing anything.
     * Cancel Transfer Job
     */
    async cancelTransferJob(requestParameters: CancelTransferJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CancelJobResponse> {
        const response = await this.cancelTransferJobRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createTransferJob without sending the request
     */
    async createTransferJobRequestOpts(requestParameters: CreateTransferJobRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['deviceId'] == null) {
            throw new runtime.RequiredError(
                'deviceId',
                'Required parameter "deviceId" was null or undefined when calling createTransferJob().'
            );
        }

        if (requestParameters['storageType'] == null) {
            throw new runtime.RequiredError(
                'storageType',
                'Required parameter "storageType" was null or undefined when calling createTransferJob().'
            );
        }

        if (requestParameters['createJobBody'] == null) {
            throw new runtime.RequiredError(
                'createJobBody',
                'Required parameter "createJobBody" was null or undefined when calling createTransferJob().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/devices/{deviceId}/storage/{storageType}/transfers`;
        urlPath = urlPath.replace('{deviceId}', encodeURIComponent(String(requestParameters['deviceId'])));
        urlPath = urlPath.replace('{storageType}', encodeURIComponent(String(requestParameters['storageType'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateJobBodyToJSON(requestParameters['createJobBody']),
        };
    }

    /**
     * Starts a new file transfer job for a device\'s storage.  - Acquires an exclusive lease on the device for the lifetime of the job - a device can only have one active transfer at a time. - Issues no device traffic - the device reset happens on the first uploaded file.
     * Create Transfer Job
     */
    async createTransferJobRaw(requestParameters: CreateTransferJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateJobResponse>> {
        const requestOptions = await this.createTransferJobRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateJobResponseFromJSON(jsonValue));
    }

    /**
     * Starts a new file transfer job for a device\'s storage.  - Acquires an exclusive lease on the device for the lifetime of the job - a device can only have one active transfer at a time. - Issues no device traffic - the device reset happens on the first uploaded file.
     * Create Transfer Job
     */
    async createTransferJob(requestParameters: CreateTransferJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateJobResponse> {
        const response = await this.createTransferJobRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getActiveTransferJob without sending the request
     */
    async getActiveTransferJobRequestOpts(requestParameters: GetActiveTransferJobRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['deviceId'] == null) {
            throw new runtime.RequiredError(
                'deviceId',
                'Required parameter "deviceId" was null or undefined when calling getActiveTransferJob().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/devices/{deviceId}/transfers/active`;
        urlPath = urlPath.replace('{deviceId}', encodeURIComponent(String(requestParameters['deviceId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets the device\'s currently active transfer job.  - Returns 200 with a null job when the device has no transfer in progress - an idle device is a normal answer, not a 404.
     * Get Active Transfer Job
     */
    async getActiveTransferJobRaw(requestParameters: GetActiveTransferJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetActiveJobResponse>> {
        const requestOptions = await this.getActiveTransferJobRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetActiveJobResponseFromJSON(jsonValue));
    }

    /**
     * Gets the device\'s currently active transfer job.  - Returns 200 with a null job when the device has no transfer in progress - an idle device is a normal answer, not a 404.
     * Get Active Transfer Job
     */
    async getActiveTransferJob(requestParameters: GetActiveTransferJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetActiveJobResponse> {
        const response = await this.getActiveTransferJobRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTransferJob without sending the request
     */
    async getTransferJobRequestOpts(requestParameters: GetTransferJobRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling getTransferJob().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/transfers/{jobId}`;
        urlPath = urlPath.replace('{jobId}', encodeURIComponent(String(requestParameters['jobId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets the current snapshot of a transfer job - the same shape the transfer hub pushes over SignalR, so a client can poll this endpoint instead of subscribing.
     * Get Transfer Job
     */
    async getTransferJobRaw(requestParameters: GetTransferJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetJobResponse>> {
        const requestOptions = await this.getTransferJobRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetJobResponseFromJSON(jsonValue));
    }

    /**
     * Gets the current snapshot of a transfer job - the same shape the transfer hub pushes over SignalR, so a client can poll this endpoint instead of subscribing.
     * Get Transfer Job
     */
    async getTransferJob(requestParameters: GetTransferJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetJobResponse> {
        const response = await this.getTransferJobRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sealTransferJob without sending the request
     */
    async sealTransferJobRequestOpts(requestParameters: SealTransferJobRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling sealTransferJob().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/transfers/{jobId}/seal`;
        urlPath = urlPath.replace('{jobId}', encodeURIComponent(String(requestParameters['jobId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Marks a transfer job as sealed - no further files will be accepted.  - Idempotent when the job is already sealed. - Rejected with a clear message when the job cannot reach Sealed from its current state. - A job sealed with an empty queue reaches Completed immediately - no upload required.
     * Seal Transfer Job
     */
    async sealTransferJobRaw(requestParameters: SealTransferJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SealJobResponse>> {
        const requestOptions = await this.sealTransferJobRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SealJobResponseFromJSON(jsonValue));
    }

    /**
     * Marks a transfer job as sealed - no further files will be accepted.  - Idempotent when the job is already sealed. - Rejected with a clear message when the job cannot reach Sealed from its current state. - A job sealed with an empty queue reaches Completed immediately - no upload required.
     * Seal Transfer Job
     */
    async sealTransferJob(requestParameters: SealTransferJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SealJobResponse> {
        const response = await this.sealTransferJobRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for uploadTransferFile without sending the request
     */
    async uploadTransferFileRequestOpts(requestParameters: UploadTransferFileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling uploadTransferFile().'
            );
        }

        if (requestParameters['path'] == null) {
            throw new runtime.RequiredError(
                'path',
                'Required parameter "path" was null or undefined when calling uploadTransferFile().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['path'] != null) {
            queryParameters['Path'] = requestParameters['path'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/transfers/{jobId}/files`;
        urlPath = urlPath.replace('{jobId}', encodeURIComponent(String(requestParameters['jobId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Streams a single file\'s raw body (application/octet-stream) into a transfer job.  - One file per request; the body is streamed straight to disk, never buffered. - Blocks until the capacity gate has a free slot instead of failing - a slow device shows up as a slower response, never as an error. - Rejected immediately (400) when the job cannot accept files, and before any file is staged when the relative path is unusable.
     * Upload Transfer File
     */
    async uploadTransferFileRaw(requestParameters: UploadTransferFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadFileResponse>> {
        const requestOptions = await this.uploadTransferFileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadFileResponseFromJSON(jsonValue));
    }

    /**
     * Streams a single file\'s raw body (application/octet-stream) into a transfer job.  - One file per request; the body is streamed straight to disk, never buffered. - Blocks until the capacity gate has a free slot instead of failing - a slow device shows up as a slower response, never as an error. - Rejected immediately (400) when the job cannot accept files, and before any file is staged when the relative path is unusable.
     * Upload Transfer File
     */
    async uploadTransferFile(requestParameters: UploadTransferFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadFileResponse> {
        const response = await this.uploadTransferFileRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
