/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1.0.0-alpha.8
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-alpha.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type GetVersionResponse,
    GetVersionResponseFromJSON,
    GetVersionResponseToJSON,
} from '../models/GetVersionResponse';
import {
    type ProblemDetails,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/ProblemDetails';

/**
 * 
 */
export class VersionApiService extends runtime.BaseAPI {

    /**
     * Creates request options for getVersion without sending the request
     */
    async getVersionRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/version`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves the current semantic version of the TeensyROM application.  The version follows semantic versioning format: **Major.Minor.Patch[-prerelease]**  **Version Information:** - **Major**: Breaking changes or significant new features - **Minor**: Backward-compatible new features - **Patch**: Backward-compatible bug fixes - **Prerelease**: Optional prerelease identifier (e.g., alpha.1, beta.2)  This version is read from the assembly metadata and matches the version specified in the TeensyRom.Api.csproj file.
     * Get Application Version
     */
    async getVersionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetVersionResponse>> {
        const requestOptions = await this.getVersionRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetVersionResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves the current semantic version of the TeensyROM application.  The version follows semantic versioning format: **Major.Minor.Patch[-prerelease]**  **Version Information:** - **Major**: Breaking changes or significant new features - **Minor**: Backward-compatible new features - **Patch**: Backward-compatible bug fixes - **Prerelease**: Optional prerelease identifier (e.g., alpha.1, beta.2)  This version is read from the assembly metadata and matches the version specified in the TeensyRom.Api.csproj file.
     * Get Application Version
     */
    async getVersion(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetVersionResponse> {
        const response = await this.getVersionRaw(initOverrides);
        return await response.value();
    }

}
