/* tslint:disable */
/* eslint-disable */
/**
 * Assembly64 API
 * Swagger documentation for Assembly64 API operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: freabe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CollectionChecksumNew,
  CollectionData,
  ContentCollection,
  ContentCollectionItem,
} from '../models/index';
import {
    CollectionChecksumNewFromJSON,
    CollectionChecksumNewToJSON,
    CollectionDataFromJSON,
    CollectionDataToJSON,
    ContentCollectionFromJSON,
    ContentCollectionToJSON,
    ContentCollectionItemFromJSON,
    ContentCollectionItemToJSON,
} from '../models/index';

export interface AddContentListToCollectionRequest {
    collectionId: number;
    contentCollectionItem: Array<ContentCollectionItem>;
    clientId?: string;
}

export interface AddContentToCollectionRequest {
    collectionId: number;
    itemId: string;
    itemCategory: number;
    clientId?: string;
}

export interface AlterCollectionRequest {
    name: string;
    _public: boolean;
    collectionId: number;
    clientId?: string;
}

export interface ChangeOrderRequest {
    collectionId: number;
    requestBody: Array<number>;
    clientId?: string;
}

export interface CopyCollectionRequest {
    collectionIdSource: number;
    collectionIdTarget: number;
    clientId?: string;
}

export interface CreateCollectionRequest {
    name: string;
    _public: boolean;
    collectionType: CreateCollectionCollectionTypeEnum;
    clientId?: string;
}

export interface DeleteCollectionRequest {
    collectionId: number;
    clientId?: string;
}

export interface DeleteContentFromCollectionRequest {
    collectionId: number;
    id: number;
    clientId?: string;
}

export interface DeleteContentListToCollectionRequest {
    collectionId: number;
    contentCollectionItem: Array<ContentCollectionItem>;
    clientId?: string;
}

export interface GetChecksumsRequest {
    collectionType: GetChecksumsCollectionTypeEnum;
    clientId?: string;
}

export interface GetCollectionRequest {
    collectionId: number;
    clientId?: string;
}

export interface GetCollectionDataRequest {
    collectionType: GetCollectionDataCollectionTypeEnum;
    clientId?: string;
}

export interface GetCollectionInfoRequest {
    collectionId: number;
    clientId?: string;
}

export interface GetCollectionItemIdsRequest {
    clientId?: string;
}

export interface GetCollectionNamesForItemIdRequest {
    itemId: string;
    clientId?: string;
}

export interface GetCollectionsRequest {
    collectionType: GetCollectionsCollectionTypeEnum;
    clientId?: string;
}

export interface GetPublicCollectionsRequest {
    collectionType: GetPublicCollectionsCollectionTypeEnum;
    clientId?: string;
}

export interface MoveSongRequest {
    collectionId: number;
    id: number;
    to: number;
    clientId?: string;
}

export interface SubscribeToCollectionRequest {
    collectionId: number;
    clientId?: string;
}

export interface UnsubscribeToCollectionRequest {
    collectionId: number;
    clientId?: string;
}

/**
 * 
 */
export class ContentCollectionsFacadeApiService extends runtime.BaseAPI {

    /**
     */
    async addContentListToCollectionRaw(requestParameters: AddContentListToCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionData>> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling addContentListToCollection().'
            );
        }

        if (requestParameters['contentCollectionItem'] == null) {
            throw new runtime.RequiredError(
                'contentCollectionItem',
                'Required parameter "contentCollectionItem" was null or undefined when calling addContentListToCollection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/contentcollections/item/{collectionId}`.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters['collectionId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['contentCollectionItem']!.map(ContentCollectionItemToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionDataFromJSON(jsonValue));
    }

    /**
     */
    async addContentListToCollection(requestParameters: AddContentListToCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionData> {
        const response = await this.addContentListToCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async addContentToCollectionRaw(requestParameters: AddContentToCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionData>> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling addContentToCollection().'
            );
        }

        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling addContentToCollection().'
            );
        }

        if (requestParameters['itemCategory'] == null) {
            throw new runtime.RequiredError(
                'itemCategory',
                'Required parameter "itemCategory" was null or undefined when calling addContentToCollection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/contentcollections/item/{collectionId}/{itemId}/{itemCategory}`.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters['collectionId']))).replace(`{${"itemId"}}`, encodeURIComponent(String(requestParameters['itemId']))).replace(`{${"itemCategory"}}`, encodeURIComponent(String(requestParameters['itemCategory']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionDataFromJSON(jsonValue));
    }

    /**
     */
    async addContentToCollection(requestParameters: AddContentToCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionData> {
        const response = await this.addContentToCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async alterCollectionRaw(requestParameters: AlterCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionData>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling alterCollection().'
            );
        }

        if (requestParameters['_public'] == null) {
            throw new runtime.RequiredError(
                '_public',
                'Required parameter "_public" was null or undefined when calling alterCollection().'
            );
        }

        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling alterCollection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/contentcollections/{collectionId}/{name}/{public}`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))).replace(`{${"public"}}`, encodeURIComponent(String(requestParameters['_public']))).replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters['collectionId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionDataFromJSON(jsonValue));
    }

    /**
     */
    async alterCollection(requestParameters: AlterCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionData> {
        const response = await this.alterCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async changeOrderRaw(requestParameters: ChangeOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionData>> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling changeOrder().'
            );
        }

        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling changeOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/contentcollections/{collectionId}/order`.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters['collectionId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionDataFromJSON(jsonValue));
    }

    /**
     */
    async changeOrder(requestParameters: ChangeOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionData> {
        const response = await this.changeOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async copyCollectionRaw(requestParameters: CopyCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionData>> {
        if (requestParameters['collectionIdSource'] == null) {
            throw new runtime.RequiredError(
                'collectionIdSource',
                'Required parameter "collectionIdSource" was null or undefined when calling copyCollection().'
            );
        }

        if (requestParameters['collectionIdTarget'] == null) {
            throw new runtime.RequiredError(
                'collectionIdTarget',
                'Required parameter "collectionIdTarget" was null or undefined when calling copyCollection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/contentcollections/{collectionIdSource}/{collectionIdTarget}/copy`.replace(`{${"collectionIdSource"}}`, encodeURIComponent(String(requestParameters['collectionIdSource']))).replace(`{${"collectionIdTarget"}}`, encodeURIComponent(String(requestParameters['collectionIdTarget']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionDataFromJSON(jsonValue));
    }

    /**
     */
    async copyCollection(requestParameters: CopyCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionData> {
        const response = await this.copyCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async createCollectionRaw(requestParameters: CreateCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionData>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling createCollection().'
            );
        }

        if (requestParameters['_public'] == null) {
            throw new runtime.RequiredError(
                '_public',
                'Required parameter "_public" was null or undefined when calling createCollection().'
            );
        }

        if (requestParameters['collectionType'] == null) {
            throw new runtime.RequiredError(
                'collectionType',
                'Required parameter "collectionType" was null or undefined when calling createCollection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/contentcollections/{collectionType}/{name}/{public}`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))).replace(`{${"public"}}`, encodeURIComponent(String(requestParameters['_public']))).replace(`{${"collectionType"}}`, encodeURIComponent(String(requestParameters['collectionType']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionDataFromJSON(jsonValue));
    }

    /**
     */
    async createCollection(requestParameters: CreateCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionData> {
        const response = await this.createCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteCollectionRaw(requestParameters: DeleteCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionData>> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling deleteCollection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/contentcollections/id/{collectionId}`.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters['collectionId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionDataFromJSON(jsonValue));
    }

    /**
     */
    async deleteCollection(requestParameters: DeleteCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionData> {
        const response = await this.deleteCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteContentFromCollectionRaw(requestParameters: DeleteContentFromCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionData>> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling deleteContentFromCollection().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteContentFromCollection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/contentcollections/item/{collectionId}/{id}`.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters['collectionId']))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionDataFromJSON(jsonValue));
    }

    /**
     */
    async deleteContentFromCollection(requestParameters: DeleteContentFromCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionData> {
        const response = await this.deleteContentFromCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteContentListToCollectionRaw(requestParameters: DeleteContentListToCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionData>> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling deleteContentListToCollection().'
            );
        }

        if (requestParameters['contentCollectionItem'] == null) {
            throw new runtime.RequiredError(
                'contentCollectionItem',
                'Required parameter "contentCollectionItem" was null or undefined when calling deleteContentListToCollection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/contentcollections/item/{collectionId}/batch`.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters['collectionId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['contentCollectionItem']!.map(ContentCollectionItemToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionDataFromJSON(jsonValue));
    }

    /**
     */
    async deleteContentListToCollection(requestParameters: DeleteContentListToCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionData> {
        const response = await this.deleteContentListToCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getChecksumsRaw(requestParameters: GetChecksumsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionChecksumNew>> {
        if (requestParameters['collectionType'] == null) {
            throw new runtime.RequiredError(
                'collectionType',
                'Required parameter "collectionType" was null or undefined when calling getChecksums().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/contentcollections/{collectionType}/checksum`.replace(`{${"collectionType"}}`, encodeURIComponent(String(requestParameters['collectionType']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionChecksumNewFromJSON(jsonValue));
    }

    /**
     */
    async getChecksums(requestParameters: GetChecksumsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionChecksumNew> {
        const response = await this.getChecksumsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getCollectionRaw(requestParameters: GetCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ContentCollectionItem>>> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling getCollection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/contentcollections/id/{collectionId}`.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters['collectionId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ContentCollectionItemFromJSON));
    }

    /**
     */
    async getCollection(requestParameters: GetCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ContentCollectionItem>> {
        const response = await this.getCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getCollectionDataRaw(requestParameters: GetCollectionDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionData>> {
        if (requestParameters['collectionType'] == null) {
            throw new runtime.RequiredError(
                'collectionType',
                'Required parameter "collectionType" was null or undefined when calling getCollectionData().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/contentcollections/{collectionType}`.replace(`{${"collectionType"}}`, encodeURIComponent(String(requestParameters['collectionType']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionDataFromJSON(jsonValue));
    }

    /**
     */
    async getCollectionData(requestParameters: GetCollectionDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionData> {
        const response = await this.getCollectionDataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getCollectionInfoRaw(requestParameters: GetCollectionInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContentCollection>> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling getCollectionInfo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/contentcollections/info/{collectionId}`.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters['collectionId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ContentCollectionFromJSON(jsonValue));
    }

    /**
     */
    async getCollectionInfo(requestParameters: GetCollectionInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContentCollection> {
        const response = await this.getCollectionInfoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getCollectionItemIdsRaw(requestParameters: GetCollectionItemIdsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/contentcollections/collectionitems`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async getCollectionItemIds(requestParameters: GetCollectionItemIdsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.getCollectionItemIdsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getCollectionNamesForItemIdRaw(requestParameters: GetCollectionNamesForItemIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling getCollectionNamesForItemId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/contentcollections/collectionnames/{itemId}`.replace(`{${"itemId"}}`, encodeURIComponent(String(requestParameters['itemId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async getCollectionNamesForItemId(requestParameters: GetCollectionNamesForItemIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.getCollectionNamesForItemIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getCollectionsRaw(requestParameters: GetCollectionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ContentCollection>>> {
        if (requestParameters['collectionType'] == null) {
            throw new runtime.RequiredError(
                'collectionType',
                'Required parameter "collectionType" was null or undefined when calling getCollections().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/contentcollections/type/{collectionType}`.replace(`{${"collectionType"}}`, encodeURIComponent(String(requestParameters['collectionType']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ContentCollectionFromJSON));
    }

    /**
     */
    async getCollections(requestParameters: GetCollectionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ContentCollection>> {
        const response = await this.getCollectionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getPublicCollectionsRaw(requestParameters: GetPublicCollectionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ContentCollection>>> {
        if (requestParameters['collectionType'] == null) {
            throw new runtime.RequiredError(
                'collectionType',
                'Required parameter "collectionType" was null or undefined when calling getPublicCollections().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/contentcollections/type/{collectionType}/public`.replace(`{${"collectionType"}}`, encodeURIComponent(String(requestParameters['collectionType']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ContentCollectionFromJSON));
    }

    /**
     */
    async getPublicCollections(requestParameters: GetPublicCollectionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ContentCollection>> {
        const response = await this.getPublicCollectionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async moveSongRaw(requestParameters: MoveSongRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionData>> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling moveSong().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling moveSong().'
            );
        }

        if (requestParameters['to'] == null) {
            throw new runtime.RequiredError(
                'to',
                'Required parameter "to" was null or undefined when calling moveSong().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/contentcollections/item/{collectionId}/move/{id}/{to}`.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters['collectionId']))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"to"}}`, encodeURIComponent(String(requestParameters['to']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionDataFromJSON(jsonValue));
    }

    /**
     */
    async moveSong(requestParameters: MoveSongRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionData> {
        const response = await this.moveSongRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async subscribeToCollectionRaw(requestParameters: SubscribeToCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionData>> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling subscribeToCollection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/contentcollections/{collectionId}/subscribe`.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters['collectionId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionDataFromJSON(jsonValue));
    }

    /**
     */
    async subscribeToCollection(requestParameters: SubscribeToCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionData> {
        const response = await this.subscribeToCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async unsubscribeToCollectionRaw(requestParameters: UnsubscribeToCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionData>> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling unsubscribeToCollection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/contentcollections/{collectionId}/subscribe`.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters['collectionId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionDataFromJSON(jsonValue));
    }

    /**
     */
    async unsubscribeToCollection(requestParameters: UnsubscribeToCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionData> {
        const response = await this.unsubscribeToCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const CreateCollectionCollectionTypeEnum = {
    Playlist: 'PLAYLIST',
    UserCollection: 'USER_COLLECTION',
    DjPlayer: 'DJ_PLAYER'
} as const;
export type CreateCollectionCollectionTypeEnum = typeof CreateCollectionCollectionTypeEnum[keyof typeof CreateCollectionCollectionTypeEnum];
/**
 * @export
 */
export const GetChecksumsCollectionTypeEnum = {
    Playlist: 'PLAYLIST',
    UserCollection: 'USER_COLLECTION',
    DjPlayer: 'DJ_PLAYER'
} as const;
export type GetChecksumsCollectionTypeEnum = typeof GetChecksumsCollectionTypeEnum[keyof typeof GetChecksumsCollectionTypeEnum];
/**
 * @export
 */
export const GetCollectionDataCollectionTypeEnum = {
    Playlist: 'PLAYLIST',
    UserCollection: 'USER_COLLECTION',
    DjPlayer: 'DJ_PLAYER'
} as const;
export type GetCollectionDataCollectionTypeEnum = typeof GetCollectionDataCollectionTypeEnum[keyof typeof GetCollectionDataCollectionTypeEnum];
/**
 * @export
 */
export const GetCollectionsCollectionTypeEnum = {
    Playlist: 'PLAYLIST',
    UserCollection: 'USER_COLLECTION',
    DjPlayer: 'DJ_PLAYER'
} as const;
export type GetCollectionsCollectionTypeEnum = typeof GetCollectionsCollectionTypeEnum[keyof typeof GetCollectionsCollectionTypeEnum];
/**
 * @export
 */
export const GetPublicCollectionsCollectionTypeEnum = {
    Playlist: 'PLAYLIST',
    UserCollection: 'USER_COLLECTION',
    DjPlayer: 'DJ_PLAYER'
} as const;
export type GetPublicCollectionsCollectionTypeEnum = typeof GetPublicCollectionsCollectionTypeEnum[keyof typeof GetPublicCollectionsCollectionTypeEnum];
