/* tslint:disable */
/* eslint-disable */
/**
 * Assembly64 API
 * Swagger documentation for Assembly64 API operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: freabe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FlipInfoEntry,
  Metadata,
} from '../models/index';
import {
    FlipInfoEntryFromJSON,
    FlipInfoEntryToJSON,
    MetadataFromJSON,
    MetadataToJSON,
} from '../models/index';

export interface CreateFlipInfoRequest {
    id: string;
    category: number;
    flipInfoEntry: Array<FlipInfoEntry>;
    clientId?: string;
}

export interface DeleteFlipInfoRequest {
    id: string;
    category: number;
    clientId?: string;
}

export interface GetAllFlipEntriesRequest {
    clientId?: string;
}

export interface GetMetadataRequest {
    id: string;
    category: number;
    clientId?: string;
}

/**
 * 
 */
export class MetadataFacadeApiService extends runtime.BaseAPI {

    /**
     */
    async createFlipInfoRaw(requestParameters: CreateFlipInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createFlipInfo().'
            );
        }

        if (requestParameters['category'] == null) {
            throw new runtime.RequiredError(
                'category',
                'Required parameter "category" was null or undefined when calling createFlipInfo().'
            );
        }

        if (requestParameters['flipInfoEntry'] == null) {
            throw new runtime.RequiredError(
                'flipInfoEntry',
                'Required parameter "flipInfoEntry" was null or undefined when calling createFlipInfo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/metadata/flipinfo/{id}/{category}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"category"}}`, encodeURIComponent(String(requestParameters['category']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['flipInfoEntry']!.map(FlipInfoEntryToJSON),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createFlipInfo(requestParameters: CreateFlipInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createFlipInfoRaw(requestParameters, initOverrides);
    }

    /**
     */
    async deleteFlipInfoRaw(requestParameters: DeleteFlipInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteFlipInfo().'
            );
        }

        if (requestParameters['category'] == null) {
            throw new runtime.RequiredError(
                'category',
                'Required parameter "category" was null or undefined when calling deleteFlipInfo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/metadata/flipinfo/{id}/{category}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"category"}}`, encodeURIComponent(String(requestParameters['category']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteFlipInfo(requestParameters: DeleteFlipInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteFlipInfoRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getAllFlipEntriesRaw(requestParameters: GetAllFlipEntriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FlipInfoEntry>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/metadata/flipinfo`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FlipInfoEntryFromJSON));
    }

    /**
     */
    async getAllFlipEntries(requestParameters: GetAllFlipEntriesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FlipInfoEntry>> {
        const response = await this.getAllFlipEntriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getMetadataRaw(requestParameters: GetMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Metadata>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getMetadata().'
            );
        }

        if (requestParameters['category'] == null) {
            throw new runtime.RequiredError(
                'category',
                'Required parameter "category" was null or undefined when calling getMetadata().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/metadata/{id}/{category}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"category"}}`, encodeURIComponent(String(requestParameters['category']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MetadataFromJSON(jsonValue));
    }

    /**
     */
    async getMetadata(requestParameters: GetMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Metadata> {
        const response = await this.getMetadataRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
