/* tslint:disable */
/* eslint-disable */
/**
 * Assembly64 API
 * Swagger documentation for Assembly64 API operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: freabe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CategoryMapping,
  ContentEntryContainerV2,
  ContentItem,
  Preset,
} from '../models/index';
import {
    CategoryMappingFromJSON,
    CategoryMappingToJSON,
    ContentEntryContainerV2FromJSON,
    ContentEntryContainerV2ToJSON,
    ContentItemFromJSON,
    ContentItemToJSON,
    PresetFromJSON,
    PresetToJSON,
} from '../models/index';

export interface AqlQueryRequest {
    query?: string;
    clientId?: string;
}

export interface AqlQuery1Request {
    offset: number;
    query?: string;
    clientId?: string;
}

export interface AqlQuery2Request {
    offset: number;
    limit: number;
    query?: string;
    clientId?: string;
}

export interface GetCategoriesRequest {
    clientId?: string;
}

export interface GetContentEntry1Request {
    itemId: string;
    categoryId: number;
    clientId?: string;
}

export interface GetFile1Request {
    itemId: string;
    categoryId: number;
    fileId: string;
    clientId?: string;
}

export interface PresetsRequest {
    clientId?: string;
}

/**
 * 
 */
export class SearchFacadeApiService extends runtime.BaseAPI {

    /**
     */
    async aqlQueryRaw(requestParameters: AqlQueryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ContentItem>>> {
        const queryParameters: any = {};

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/search/aql`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ContentItemFromJSON));
    }

    /**
     */
    async aqlQuery(requestParameters: AqlQueryRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ContentItem>> {
        const response = await this.aqlQueryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async aqlQuery1Raw(requestParameters: AqlQuery1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ContentItem>>> {
        if (requestParameters['offset'] == null) {
            throw new runtime.RequiredError(
                'offset',
                'Required parameter "offset" was null or undefined when calling aqlQuery1().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/search/aql/{offset}`.replace(`{${"offset"}}`, encodeURIComponent(String(requestParameters['offset']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ContentItemFromJSON));
    }

    /**
     */
    async aqlQuery1(requestParameters: AqlQuery1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ContentItem>> {
        const response = await this.aqlQuery1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async aqlQuery2Raw(requestParameters: AqlQuery2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ContentItem>>> {
        if (requestParameters['offset'] == null) {
            throw new runtime.RequiredError(
                'offset',
                'Required parameter "offset" was null or undefined when calling aqlQuery2().'
            );
        }

        if (requestParameters['limit'] == null) {
            throw new runtime.RequiredError(
                'limit',
                'Required parameter "limit" was null or undefined when calling aqlQuery2().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/search/aql/{offset}/{limit}`.replace(`{${"offset"}}`, encodeURIComponent(String(requestParameters['offset']))).replace(`{${"limit"}}`, encodeURIComponent(String(requestParameters['limit']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ContentItemFromJSON));
    }

    /**
     */
    async aqlQuery2(requestParameters: AqlQuery2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ContentItem>> {
        const response = await this.aqlQuery2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getCategoriesRaw(requestParameters: GetCategoriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CategoryMapping>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/search/categories`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CategoryMappingFromJSON));
    }

    /**
     */
    async getCategories(requestParameters: GetCategoriesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CategoryMapping>> {
        const response = await this.getCategoriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getContentEntry1Raw(requestParameters: GetContentEntry1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContentEntryContainerV2>> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling getContentEntry1().'
            );
        }

        if (requestParameters['categoryId'] == null) {
            throw new runtime.RequiredError(
                'categoryId',
                'Required parameter "categoryId" was null or undefined when calling getContentEntry1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/search/entries/{itemId}/{categoryId}`.replace(`{${"itemId"}}`, encodeURIComponent(String(requestParameters['itemId']))).replace(`{${"categoryId"}}`, encodeURIComponent(String(requestParameters['categoryId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ContentEntryContainerV2FromJSON(jsonValue));
    }

    /**
     */
    async getContentEntry1(requestParameters: GetContentEntry1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContentEntryContainerV2> {
        const response = await this.getContentEntry1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getFile1Raw(requestParameters: GetFile1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling getFile1().'
            );
        }

        if (requestParameters['categoryId'] == null) {
            throw new runtime.RequiredError(
                'categoryId',
                'Required parameter "categoryId" was null or undefined when calling getFile1().'
            );
        }

        if (requestParameters['fileId'] == null) {
            throw new runtime.RequiredError(
                'fileId',
                'Required parameter "fileId" was null or undefined when calling getFile1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/search/bin/{itemId}/{categoryId}/{fileId}`.replace(`{${"itemId"}}`, encodeURIComponent(String(requestParameters['itemId']))).replace(`{${"categoryId"}}`, encodeURIComponent(String(requestParameters['categoryId']))).replace(`{${"fileId"}}`, encodeURIComponent(String(requestParameters['fileId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async getFile1(requestParameters: GetFile1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.getFile1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async presetsRaw(requestParameters: PresetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Preset>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/search/aql/presets`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PresetFromJSON));
    }

    /**
     */
    async presets(requestParameters: PresetsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Preset>> {
        const response = await this.presetsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
