/* tslint:disable */
/* eslint-disable */
/**
 * Assembly64 API
 * Swagger documentation for Assembly64 API operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: freabe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CompoType,
  ContentEntryV2,
  ContentItem,
} from '../models/index';
import {
    CompoTypeFromJSON,
    CompoTypeToJSON,
    ContentEntryV2FromJSON,
    ContentEntryV2ToJSON,
    ContentItemFromJSON,
    ContentItemToJSON,
} from '../models/index';

export interface FileExistRequest {
    itemId: string;
    categoryId: number;
    fileId: string;
    clientId?: string;
}

export interface FileExistAsDirectContentRequest {
    itemId: string;
    categoryId: number;
    clientId?: string;
}

export interface GetCompoTypesRequest {
    clientId?: string;
}

export interface GetContentEntryRequest {
    itemId: string;
    categoryId: number;
    fileId: number;
    clientId?: string;
}

export interface GetFileRequest {
    itemId: string;
    categoryId: number;
    clientId?: string;
}

export interface GetFile2Request {
    itemEntryId: number;
    clientId?: string;
}

export interface GetGroupsByNameRequest {
    groupname: string;
    category: number;
    clientId?: string;
}

export interface GetGroupsByNameAndYearRequest {
    groupname: string;
    category: number;
    year: number;
    clientId?: string;
}

export interface GetGroupsByReleaseRequest {
    release: string;
    category: number;
    clientId?: string;
}

export interface GetHandlesByNameRequest {
    handle: string;
    category: number;
    clientId?: string;
}

export interface GetMetadataForItemRequest {
    id: string;
    category: number;
    clientId?: string;
}

export interface GetReleaseGroupForReleaseRequest {
    release: string;
    category: number;
    clientId?: string;
}

/**
 * 
 */
export class SearchAdvancedFacadeApiService extends runtime.BaseAPI {

    /**
     */
    async fileExistRaw(requestParameters: FileExistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling fileExist().'
            );
        }

        if (requestParameters['categoryId'] == null) {
            throw new runtime.RequiredError(
                'categoryId',
                'Required parameter "categoryId" was null or undefined when calling fileExist().'
            );
        }

        if (requestParameters['fileId'] == null) {
            throw new runtime.RequiredError(
                'fileId',
                'Required parameter "fileId" was null or undefined when calling fileExist().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/search/{itemId}/{categoryId}/{fileId}/exist`.replace(`{${"itemId"}}`, encodeURIComponent(String(requestParameters['itemId']))).replace(`{${"categoryId"}}`, encodeURIComponent(String(requestParameters['categoryId']))).replace(`{${"fileId"}}`, encodeURIComponent(String(requestParameters['fileId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async fileExist(requestParameters: FileExistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.fileExistRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async fileExistAsDirectContentRaw(requestParameters: FileExistAsDirectContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling fileExistAsDirectContent().'
            );
        }

        if (requestParameters['categoryId'] == null) {
            throw new runtime.RequiredError(
                'categoryId',
                'Required parameter "categoryId" was null or undefined when calling fileExistAsDirectContent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/search/{itemId}/{categoryId}/exist`.replace(`{${"itemId"}}`, encodeURIComponent(String(requestParameters['itemId']))).replace(`{${"categoryId"}}`, encodeURIComponent(String(requestParameters['categoryId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async fileExistAsDirectContent(requestParameters: FileExistAsDirectContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.fileExistAsDirectContentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getCompoTypesRaw(requestParameters: GetCompoTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CompoType>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/search/compotypes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CompoTypeFromJSON));
    }

    /**
     */
    async getCompoTypes(requestParameters: GetCompoTypesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CompoType>> {
        const response = await this.getCompoTypesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getContentEntryRaw(requestParameters: GetContentEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContentEntryV2>> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling getContentEntry().'
            );
        }

        if (requestParameters['categoryId'] == null) {
            throw new runtime.RequiredError(
                'categoryId',
                'Required parameter "categoryId" was null or undefined when calling getContentEntry().'
            );
        }

        if (requestParameters['fileId'] == null) {
            throw new runtime.RequiredError(
                'fileId',
                'Required parameter "fileId" was null or undefined when calling getContentEntry().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/search/entry/{itemId}/{categoryId}/{fileId}`.replace(`{${"itemId"}}`, encodeURIComponent(String(requestParameters['itemId']))).replace(`{${"categoryId"}}`, encodeURIComponent(String(requestParameters['categoryId']))).replace(`{${"fileId"}}`, encodeURIComponent(String(requestParameters['fileId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ContentEntryV2FromJSON(jsonValue));
    }

    /**
     */
    async getContentEntry(requestParameters: GetContentEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContentEntryV2> {
        const response = await this.getContentEntryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getFileRaw(requestParameters: GetFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling getFile().'
            );
        }

        if (requestParameters['categoryId'] == null) {
            throw new runtime.RequiredError(
                'categoryId',
                'Required parameter "categoryId" was null or undefined when calling getFile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/search/zip/{itemId}/{categoryId}`.replace(`{${"itemId"}}`, encodeURIComponent(String(requestParameters['itemId']))).replace(`{${"categoryId"}}`, encodeURIComponent(String(requestParameters['categoryId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async getFile(requestParameters: GetFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.getFileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getFile2Raw(requestParameters: GetFile2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['itemEntryId'] == null) {
            throw new runtime.RequiredError(
                'itemEntryId',
                'Required parameter "itemEntryId" was null or undefined when calling getFile2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/search/bin/{itemEntryId}`.replace(`{${"itemEntryId"}}`, encodeURIComponent(String(requestParameters['itemEntryId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async getFile2(requestParameters: GetFile2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.getFile2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getGroupsByNameRaw(requestParameters: GetGroupsByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        if (requestParameters['groupname'] == null) {
            throw new runtime.RequiredError(
                'groupname',
                'Required parameter "groupname" was null or undefined when calling getGroupsByName().'
            );
        }

        if (requestParameters['category'] == null) {
            throw new runtime.RequiredError(
                'category',
                'Required parameter "category" was null or undefined when calling getGroupsByName().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/search/groups/{groupname}/{category}`.replace(`{${"groupname"}}`, encodeURIComponent(String(requestParameters['groupname']))).replace(`{${"category"}}`, encodeURIComponent(String(requestParameters['category']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async getGroupsByName(requestParameters: GetGroupsByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.getGroupsByNameRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getGroupsByNameAndYearRaw(requestParameters: GetGroupsByNameAndYearRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        if (requestParameters['groupname'] == null) {
            throw new runtime.RequiredError(
                'groupname',
                'Required parameter "groupname" was null or undefined when calling getGroupsByNameAndYear().'
            );
        }

        if (requestParameters['category'] == null) {
            throw new runtime.RequiredError(
                'category',
                'Required parameter "category" was null or undefined when calling getGroupsByNameAndYear().'
            );
        }

        if (requestParameters['year'] == null) {
            throw new runtime.RequiredError(
                'year',
                'Required parameter "year" was null or undefined when calling getGroupsByNameAndYear().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/search/groups/{groupname}/{category}/{year}`.replace(`{${"groupname"}}`, encodeURIComponent(String(requestParameters['groupname']))).replace(`{${"category"}}`, encodeURIComponent(String(requestParameters['category']))).replace(`{${"year"}}`, encodeURIComponent(String(requestParameters['year']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async getGroupsByNameAndYear(requestParameters: GetGroupsByNameAndYearRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.getGroupsByNameAndYearRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getGroupsByReleaseRaw(requestParameters: GetGroupsByReleaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        if (requestParameters['release'] == null) {
            throw new runtime.RequiredError(
                'release',
                'Required parameter "release" was null or undefined when calling getGroupsByRelease().'
            );
        }

        if (requestParameters['category'] == null) {
            throw new runtime.RequiredError(
                'category',
                'Required parameter "category" was null or undefined when calling getGroupsByRelease().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/search/releases/{release}/{category}`.replace(`{${"release"}}`, encodeURIComponent(String(requestParameters['release']))).replace(`{${"category"}}`, encodeURIComponent(String(requestParameters['category']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async getGroupsByRelease(requestParameters: GetGroupsByReleaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.getGroupsByReleaseRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getHandlesByNameRaw(requestParameters: GetHandlesByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        if (requestParameters['handle'] == null) {
            throw new runtime.RequiredError(
                'handle',
                'Required parameter "handle" was null or undefined when calling getHandlesByName().'
            );
        }

        if (requestParameters['category'] == null) {
            throw new runtime.RequiredError(
                'category',
                'Required parameter "category" was null or undefined when calling getHandlesByName().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/search/handles/{handle}/{category}`.replace(`{${"handle"}}`, encodeURIComponent(String(requestParameters['handle']))).replace(`{${"category"}}`, encodeURIComponent(String(requestParameters['category']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async getHandlesByName(requestParameters: GetHandlesByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.getHandlesByNameRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getMetadataForItemRaw(requestParameters: GetMetadataForItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContentItem>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getMetadataForItem().'
            );
        }

        if (requestParameters['category'] == null) {
            throw new runtime.RequiredError(
                'category',
                'Required parameter "category" was null or undefined when calling getMetadataForItem().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/search/meta/{id}/{category}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"category"}}`, encodeURIComponent(String(requestParameters['category']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ContentItemFromJSON(jsonValue));
    }

    /**
     */
    async getMetadataForItem(requestParameters: GetMetadataForItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContentItem> {
        const response = await this.getMetadataForItemRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getReleaseGroupForReleaseRaw(requestParameters: GetReleaseGroupForReleaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ContentItem>>> {
        if (requestParameters['release'] == null) {
            throw new runtime.RequiredError(
                'release',
                'Required parameter "release" was null or undefined when calling getReleaseGroupForRelease().'
            );
        }

        if (requestParameters['category'] == null) {
            throw new runtime.RequiredError(
                'category',
                'Required parameter "category" was null or undefined when calling getReleaseGroupForRelease().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/search/releasegroup/{release}/{category}`.replace(`{${"release"}}`, encodeURIComponent(String(requestParameters['release']))).replace(`{${"category"}}`, encodeURIComponent(String(requestParameters['category']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ContentItemFromJSON));
    }

    /**
     */
    async getReleaseGroupForRelease(requestParameters: GetReleaseGroupForReleaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ContentItem>> {
        const response = await this.getReleaseGroupForReleaseRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
