/* tslint:disable */
/* eslint-disable */
/**
 * Assembly64 API
 * Swagger documentation for Assembly64 API operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: freabe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Backer,
  Settings,
  UserLite,
  UserSystemNotification,
} from '../models/index';
import {
    BackerFromJSON,
    BackerToJSON,
    SettingsFromJSON,
    SettingsToJSON,
    UserLiteFromJSON,
    UserLiteToJSON,
    UserSystemNotificationFromJSON,
    UserSystemNotificationToJSON,
} from '../models/index';

export interface BackersRequest {
    clientId?: string;
}

export interface FeedbackRequest {
    body: string;
    clientId?: string;
}

export interface ForgotpwdRequest {
    email: string;
    clientId?: string;
}

export interface GetAliasForPublicPlayslistsRequest {
    clientId?: string;
}

export interface GetAvatarRequest {
    id: number;
    clientId?: string;
}

export interface GetAvatarImageNameRequest {
    id: number;
    clientId?: string;
}

export interface GetSettingsRequest {
    clientId?: string;
}

export interface GetUsersOnlineRequest {
    clientId?: string;
}

export interface HeroesRequest {
    clientId?: string;
}

export interface ListUsersRequest {
    clientId?: string;
}

export interface LoginRequest {
    email: string;
    password: string;
    clientId?: string;
}

export interface LoginLiteRequest {
    email: string;
    password: string;
    clientId?: string;
}

export interface LogoutRequest {
    email: string;
    token: string;
    clientId?: string;
}

export interface RegisterRequest {
    email: string;
    password: string;
    clientId?: string;
}

export interface StoreAliasRequest {
    body: string;
    clientId?: string;
}

export interface StoreSettingsRequest {
    settings: Settings;
    clientId?: string;
}

export interface TokenLoginRequest {
    email: string;
    token: string;
    clientId?: string;
}

export interface UploadAvatarRequest {
    filename: string;
    body: string;
    clientId?: string;
}

export interface UserSystemNotificationRequest {
    userSystemNotification: UserSystemNotification;
    clientId?: string;
}

export interface ValidateRequest {
    email: string;
    token: string;
    clientId?: string;
}

export interface ValidatePasswordRequest {
    pwd: string;
    email: string;
    token: string;
    clientId?: string;
}

/**
 * 
 */
export class UserFacadeApiService extends runtime.BaseAPI {

    /**
     */
    async backersRaw(requestParameters: BackersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/user/backers`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async backers(requestParameters: BackersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.backersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async feedbackRaw(requestParameters: FeedbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling feedback().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/user/feedback`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async feedback(requestParameters: FeedbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.feedbackRaw(requestParameters, initOverrides);
    }

    /**
     */
    async forgotpwdRaw(requestParameters: ForgotpwdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['email'] == null) {
            throw new runtime.RequiredError(
                'email',
                'Required parameter "email" was null or undefined when calling forgotpwd().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/user/forgotpassword/{email}`.replace(`{${"email"}}`, encodeURIComponent(String(requestParameters['email']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async forgotpwd(requestParameters: ForgotpwdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.forgotpwdRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getAliasForPublicPlayslistsRaw(requestParameters: GetAliasForPublicPlayslistsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/user/aliasforpublicplaylists`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async getAliasForPublicPlayslists(requestParameters: GetAliasForPublicPlayslistsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.getAliasForPublicPlayslistsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getAvatarRaw(requestParameters: GetAvatarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getAvatar().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/user/avatar/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async getAvatar(requestParameters: GetAvatarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.getAvatarRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getAvatarImageNameRaw(requestParameters: GetAvatarImageNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getAvatarImageName().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/user/avatar/name/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async getAvatarImageName(requestParameters: GetAvatarImageNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.getAvatarImageNameRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getSettingsRaw(requestParameters: GetSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Settings>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/user/settings`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SettingsFromJSON(jsonValue));
    }

    /**
     */
    async getSettings(requestParameters: GetSettingsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Settings> {
        const response = await this.getSettingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getUsersOnlineRaw(requestParameters: GetUsersOnlineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/user/usersonline`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async getUsersOnline(requestParameters: GetUsersOnlineRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.getUsersOnlineRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async heroesRaw(requestParameters: HeroesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/user/heroes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async heroes(requestParameters: HeroesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.heroesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async listUsersRaw(requestParameters: ListUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Backer>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/user/donations`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BackerFromJSON));
    }

    /**
     */
    async listUsers(requestParameters: ListUsersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Backer>> {
        const response = await this.listUsersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async loginRaw(requestParameters: LoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserLite>> {
        if (requestParameters['email'] == null) {
            throw new runtime.RequiredError(
                'email',
                'Required parameter "email" was null or undefined when calling login().'
            );
        }

        if (requestParameters['password'] == null) {
            throw new runtime.RequiredError(
                'password',
                'Required parameter "password" was null or undefined when calling login().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/user/login/{email}/{password}`.replace(`{${"email"}}`, encodeURIComponent(String(requestParameters['email']))).replace(`{${"password"}}`, encodeURIComponent(String(requestParameters['password']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserLiteFromJSON(jsonValue));
    }

    /**
     */
    async login(requestParameters: LoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserLite> {
        const response = await this.loginRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async loginLiteRaw(requestParameters: LoginLiteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserLite>> {
        if (requestParameters['email'] == null) {
            throw new runtime.RequiredError(
                'email',
                'Required parameter "email" was null or undefined when calling loginLite().'
            );
        }

        if (requestParameters['password'] == null) {
            throw new runtime.RequiredError(
                'password',
                'Required parameter "password" was null or undefined when calling loginLite().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/user/login/lite/{email}/{password}`.replace(`{${"email"}}`, encodeURIComponent(String(requestParameters['email']))).replace(`{${"password"}}`, encodeURIComponent(String(requestParameters['password']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserLiteFromJSON(jsonValue));
    }

    /**
     */
    async loginLite(requestParameters: LoginLiteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserLite> {
        const response = await this.loginLiteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async logoutRaw(requestParameters: LogoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['email'] == null) {
            throw new runtime.RequiredError(
                'email',
                'Required parameter "email" was null or undefined when calling logout().'
            );
        }

        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling logout().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['email'] != null) {
            headerParameters['email'] = String(requestParameters['email']);
        }

        if (requestParameters['token'] != null) {
            headerParameters['token'] = String(requestParameters['token']);
        }

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/user/logout`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async logout(requestParameters: LogoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.logoutRaw(requestParameters, initOverrides);
    }

    /**
     */
    async registerRaw(requestParameters: RegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['email'] == null) {
            throw new runtime.RequiredError(
                'email',
                'Required parameter "email" was null or undefined when calling register().'
            );
        }

        if (requestParameters['password'] == null) {
            throw new runtime.RequiredError(
                'password',
                'Required parameter "password" was null or undefined when calling register().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/user/register/{email}/{password}`.replace(`{${"email"}}`, encodeURIComponent(String(requestParameters['email']))).replace(`{${"password"}}`, encodeURIComponent(String(requestParameters['password']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async register(requestParameters: RegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.registerRaw(requestParameters, initOverrides);
    }

    /**
     */
    async storeAliasRaw(requestParameters: StoreAliasRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling storeAlias().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/user/aliasforpublicplaylists`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async storeAlias(requestParameters: StoreAliasRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.storeAliasRaw(requestParameters, initOverrides);
    }

    /**
     */
    async storeSettingsRaw(requestParameters: StoreSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['settings'] == null) {
            throw new runtime.RequiredError(
                'settings',
                'Required parameter "settings" was null or undefined when calling storeSettings().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/user/settings`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SettingsToJSON(requestParameters['settings']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async storeSettings(requestParameters: StoreSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.storeSettingsRaw(requestParameters, initOverrides);
    }

    /**
     */
    async tokenLoginRaw(requestParameters: TokenLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserLite>> {
        if (requestParameters['email'] == null) {
            throw new runtime.RequiredError(
                'email',
                'Required parameter "email" was null or undefined when calling tokenLogin().'
            );
        }

        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling tokenLogin().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/user/tokenlogin/{email}/{token}`.replace(`{${"email"}}`, encodeURIComponent(String(requestParameters['email']))).replace(`{${"token"}}`, encodeURIComponent(String(requestParameters['token']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserLiteFromJSON(jsonValue));
    }

    /**
     */
    async tokenLogin(requestParameters: TokenLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserLite> {
        const response = await this.tokenLoginRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async uploadAvatarRaw(requestParameters: UploadAvatarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['filename'] == null) {
            throw new runtime.RequiredError(
                'filename',
                'Required parameter "filename" was null or undefined when calling uploadAvatar().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling uploadAvatar().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/user/avatar/{filename}`.replace(`{${"filename"}}`, encodeURIComponent(String(requestParameters['filename']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async uploadAvatar(requestParameters: UploadAvatarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.uploadAvatarRaw(requestParameters, initOverrides);
    }

    /**
     */
    async userSystemNotificationRaw(requestParameters: UserSystemNotificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['userSystemNotification'] == null) {
            throw new runtime.RequiredError(
                'userSystemNotification',
                'Required parameter "userSystemNotification" was null or undefined when calling userSystemNotification().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/user/userSystemNotification`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UserSystemNotificationToJSON(requestParameters['userSystemNotification']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async userSystemNotification(requestParameters: UserSystemNotificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.userSystemNotificationRaw(requestParameters, initOverrides);
    }

    /**
     */
    async validateRaw(requestParameters: ValidateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['email'] == null) {
            throw new runtime.RequiredError(
                'email',
                'Required parameter "email" was null or undefined when calling validate().'
            );
        }

        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling validate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/user/validate/{email}/{token}`.replace(`{${"email"}}`, encodeURIComponent(String(requestParameters['email']))).replace(`{${"token"}}`, encodeURIComponent(String(requestParameters['token']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async validate(requestParameters: ValidateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.validateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async validatePasswordRaw(requestParameters: ValidatePasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['pwd'] == null) {
            throw new runtime.RequiredError(
                'pwd',
                'Required parameter "pwd" was null or undefined when calling validatePassword().'
            );
        }

        if (requestParameters['email'] == null) {
            throw new runtime.RequiredError(
                'email',
                'Required parameter "email" was null or undefined when calling validatePassword().'
            );
        }

        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling validatePassword().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['clientId'] != null) {
            headerParameters['client-id'] = String(requestParameters['clientId']);
        }

        const response = await this.request({
            path: `/user/validatepassword/{token}/{email}/{pwd}`.replace(`{${"pwd"}}`, encodeURIComponent(String(requestParameters['pwd']))).replace(`{${"email"}}`, encodeURIComponent(String(requestParameters['email']))).replace(`{${"token"}}`, encodeURIComponent(String(requestParameters['token']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async validatePassword(requestParameters: ValidatePasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.validatePasswordRaw(requestParameters, initOverrides);
    }

}
