/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1.0.0-alpha.8
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-alpha.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppSettingsDto
 */
export interface AppSettingsDto {
    /**
     * 
     * @type {boolean}
     * @memberof AppSettingsDto
     */
    firstTimeSetup: boolean;
}

/**
 * Check if a given object implements the AppSettingsDto interface.
 */
export function instanceOfAppSettingsDto(value: object): value is AppSettingsDto {
    if (!('firstTimeSetup' in value) || value['firstTimeSetup'] === undefined) return false;
    return true;
}

export function AppSettingsDtoFromJSON(json: any): AppSettingsDto {
    return AppSettingsDtoFromJSONTyped(json, false);
}

export function AppSettingsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppSettingsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'firstTimeSetup': json['firstTimeSetup'],
    };
}

export function AppSettingsDtoToJSON(json: any): AppSettingsDto {
    return AppSettingsDtoToJSONTyped(json, false);
}

export function AppSettingsDtoToJSONTyped(value?: AppSettingsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'firstTimeSetup': value['firstTimeSetup'],
    };
}

