/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1.0.0-alpha.8
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-alpha.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AudioDeviceDto
 */
export interface AudioDeviceDto {
    /**
     * 
     * @type {number}
     * @memberof AudioDeviceDto
     */
    index: number;
    /**
     * 
     * @type {string}
     * @memberof AudioDeviceDto
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof AudioDeviceDto
     */
    maxInputChannels: number;
    /**
     * 
     * @type {number}
     * @memberof AudioDeviceDto
     */
    defaultSampleRate: number;
}

/**
 * Check if a given object implements the AudioDeviceDto interface.
 */
export function instanceOfAudioDeviceDto(value: object): value is AudioDeviceDto {
    if (!('index' in value) || value['index'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('maxInputChannels' in value) || value['maxInputChannels'] === undefined) return false;
    if (!('defaultSampleRate' in value) || value['defaultSampleRate'] === undefined) return false;
    return true;
}

export function AudioDeviceDtoFromJSON(json: any): AudioDeviceDto {
    return AudioDeviceDtoFromJSONTyped(json, false);
}

export function AudioDeviceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AudioDeviceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'index': json['index'],
        'name': json['name'],
        'maxInputChannels': json['maxInputChannels'],
        'defaultSampleRate': json['defaultSampleRate'],
    };
}

export function AudioDeviceDtoToJSON(json: any): AudioDeviceDto {
    return AudioDeviceDtoToJSONTyped(json, false);
}

export function AudioDeviceDtoToJSONTyped(value?: AudioDeviceDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'index': value['index'],
        'name': value['name'],
        'maxInputChannels': value['maxInputChannels'],
        'defaultSampleRate': value['defaultSampleRate'],
    };
}

