/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1.0.0-alpha.8
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-alpha.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChannelConfigDto } from './ChannelConfigDto';
import {
    ChannelConfigDtoFromJSON,
    ChannelConfigDtoFromJSONTyped,
    ChannelConfigDtoToJSON,
    ChannelConfigDtoToJSONTyped,
} from './ChannelConfigDto';

/**
 *
 * @export
 * @interface AudioSettingsDto
 */
export interface AudioSettingsDto {
    /**
     *
     * @type {boolean}
     * @memberof AudioSettingsDto
     */
    enableAudioStream: boolean;
    /**
     *
     * @type {number}
     * @memberof AudioSettingsDto
     */
    audioDeviceIndex: number;
    /**
     *
     * @type {string}
     * @memberof AudioSettingsDto
     */
    audioDeviceName: string;
    /**
     *
     * @type {number}
     * @memberof AudioSettingsDto
     */
    captureChannelCount: number;
    /**
     *
     * @type {number}
     * @memberof AudioSettingsDto
     */
    sampleRate: number;
    /**
     *
     * @type {Array<ChannelConfigDto>}
     * @memberof AudioSettingsDto
     */
    channels: Array<ChannelConfigDto>;
    /**
     * When true, audio is compressed using Opus codec (~16 KB/s per channel).
     * When false, raw PCM is sent for lowest latency (~188 KB/s per channel).
     * @type {boolean}
     * @memberof AudioSettingsDto
     */
    useOpusEncoding: boolean;
}

/**
 * Check if a given object implements the AudioSettingsDto interface.
 */
export function instanceOfAudioSettingsDto(value: object): value is AudioSettingsDto {
    if (!('enableAudioStream' in value) || value['enableAudioStream'] === undefined) return false;
    if (!('audioDeviceIndex' in value) || value['audioDeviceIndex'] === undefined) return false;
    if (!('audioDeviceName' in value) || value['audioDeviceName'] === undefined) return false;
    if (!('captureChannelCount' in value) || value['captureChannelCount'] === undefined) return false;
    if (!('sampleRate' in value) || value['sampleRate'] === undefined) return false;
    if (!('channels' in value) || value['channels'] === undefined) return false;
    // useOpusEncoding is optional with default true, so we don't require it
    return true;
}

export function AudioSettingsDtoFromJSON(json: any): AudioSettingsDto {
    return AudioSettingsDtoFromJSONTyped(json, false);
}

export function AudioSettingsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AudioSettingsDto {
    if (json == null) {
        return json;
    }
    return {

        'enableAudioStream': json['enableAudioStream'],
        'audioDeviceIndex': json['audioDeviceIndex'],
        'audioDeviceName': json['audioDeviceName'],
        'captureChannelCount': json['captureChannelCount'],
        'sampleRate': json['sampleRate'],
        'channels': ((json['channels'] as Array<any>).map(ChannelConfigDtoFromJSON)),
        'useOpusEncoding': json['useOpusEncoding'] ?? true,
    };
}

export function AudioSettingsDtoToJSON(json: any): AudioSettingsDto {
    return AudioSettingsDtoToJSONTyped(json, false);
}

export function AudioSettingsDtoToJSONTyped(value?: AudioSettingsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'enableAudioStream': value['enableAudioStream'],
        'audioDeviceIndex': value['audioDeviceIndex'],
        'audioDeviceName': value['audioDeviceName'],
        'captureChannelCount': value['captureChannelCount'],
        'sampleRate': value['sampleRate'],
        'channels': ((value['channels'] as Array<any>).map(ChannelConfigDtoToJSON)),
        'useOpusEncoding': value['useOpusEncoding'],
    };
}

