/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1.0.0-alpha.8
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-alpha.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransferJobDto } from './TransferJobDto';
import {
    TransferJobDtoFromJSON,
    TransferJobDtoFromJSONTyped,
    TransferJobDtoToJSON,
    TransferJobDtoToJSONTyped,
} from './TransferJobDto';

/**
 * 
 * @export
 * @interface CancelJobResponse
 */
export interface CancelJobResponse {
    /**
     * 
     * @type {TransferJobDto}
     * @memberof CancelJobResponse
     */
    job: TransferJobDto;
}

/**
 * Check if a given object implements the CancelJobResponse interface.
 */
export function instanceOfCancelJobResponse(value: object): value is CancelJobResponse {
    if (!('job' in value) || value['job'] === undefined) return false;
    return true;
}

export function CancelJobResponseFromJSON(json: any): CancelJobResponse {
    return CancelJobResponseFromJSONTyped(json, false);
}

export function CancelJobResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CancelJobResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'job': TransferJobDtoFromJSON(json['job']),
    };
}

export function CancelJobResponseToJSON(json: any): CancelJobResponse {
    return CancelJobResponseToJSONTyped(json, false);
}

export function CancelJobResponseToJSONTyped(value?: CancelJobResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'job': TransferJobDtoToJSON(value['job']),
    };
}

