/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1.0.0-alpha.8
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-alpha.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChannelConfigDto
 */
export interface ChannelConfigDto {
    /**
     * 
     * @type {number}
     * @memberof ChannelConfigDto
     */
    sourceChannel: number;
    /**
     * 
     * @type {boolean}
     * @memberof ChannelConfigDto
     */
    enabled: boolean;
}

/**
 * Check if a given object implements the ChannelConfigDto interface.
 */
export function instanceOfChannelConfigDto(value: object): value is ChannelConfigDto {
    if (!('sourceChannel' in value) || value['sourceChannel'] === undefined) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    return true;
}

export function ChannelConfigDtoFromJSON(json: any): ChannelConfigDto {
    return ChannelConfigDtoFromJSONTyped(json, false);
}

export function ChannelConfigDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelConfigDto {
    if (json == null) {
        return json;
    }
    return {
        
        'sourceChannel': json['sourceChannel'],
        'enabled': json['enabled'],
    };
}

export function ChannelConfigDtoToJSON(json: any): ChannelConfigDto {
    return ChannelConfigDtoToJSONTyped(json, false);
}

export function ChannelConfigDtoToJSONTyped(value?: ChannelConfigDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sourceChannel': value['sourceChannel'],
        'enabled': value['enabled'],
    };
}

