/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1.0.0-alpha.8
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-alpha.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CartDto } from './CartDto';
import {
    CartDtoFromJSON,
    CartDtoFromJSONTyped,
    CartDtoToJSON,
    CartDtoToJSONTyped,
} from './CartDto';

/**
 * 
 * @export
 * @interface ConnectTcpDeviceResponse
 */
export interface ConnectTcpDeviceResponse {
    /**
     * 
     * @type {CartDto}
     * @memberof ConnectTcpDeviceResponse
     */
    device: CartDto;
    /**
     * 
     * @type {string}
     * @memberof ConnectTcpDeviceResponse
     */
    message: string;
}

/**
 * Check if a given object implements the ConnectTcpDeviceResponse interface.
 */
export function instanceOfConnectTcpDeviceResponse(value: object): value is ConnectTcpDeviceResponse {
    if (!('device' in value) || value['device'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ConnectTcpDeviceResponseFromJSON(json: any): ConnectTcpDeviceResponse {
    return ConnectTcpDeviceResponseFromJSONTyped(json, false);
}

export function ConnectTcpDeviceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectTcpDeviceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'device': CartDtoFromJSON(json['device']),
        'message': json['message'],
    };
}

export function ConnectTcpDeviceResponseToJSON(json: any): ConnectTcpDeviceResponse {
    return ConnectTcpDeviceResponseToJSONTyped(json, false);
}

export function ConnectTcpDeviceResponseToJSONTyped(value?: ConnectTcpDeviceResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'device': CartDtoToJSON(value['device']),
        'message': value['message'],
    };
}

