/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1.0.0-alpha.7
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-alpha.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConnectionSettingsDto
 */
export interface ConnectionSettingsDto {
    /**
     * 
     * @type {boolean}
     * @memberof ConnectionSettingsDto
     */
    autoConnectEnabled: boolean;
}

/**
 * Check if a given object implements the ConnectionSettingsDto interface.
 */
export function instanceOfConnectionSettingsDto(value: object): value is ConnectionSettingsDto {
    if (!('autoConnectEnabled' in value) || value['autoConnectEnabled'] === undefined) return false;
    return true;
}

export function ConnectionSettingsDtoFromJSON(json: any): ConnectionSettingsDto {
    return ConnectionSettingsDtoFromJSONTyped(json, false);
}

export function ConnectionSettingsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionSettingsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'autoConnectEnabled': json['autoConnectEnabled'],
    };
}

export function ConnectionSettingsDtoToJSON(json: any): ConnectionSettingsDto {
    return ConnectionSettingsDtoToJSONTyped(json, false);
}

export function ConnectionSettingsDtoToJSONTyped(value?: ConnectionSettingsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'autoConnectEnabled': value['autoConnectEnabled'],
    };
}

