/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConnectionType } from './ConnectionType';
import {
    ConnectionTypeFromJSON,
    ConnectionTypeFromJSONTyped,
    ConnectionTypeToJSON,
    ConnectionTypeToJSONTyped,
} from './ConnectionType';
import type { SerialConnectionSettingsDto } from './SerialConnectionSettingsDto';
import {
    SerialConnectionSettingsDtoFromJSON,
    SerialConnectionSettingsDtoFromJSONTyped,
    SerialConnectionSettingsDtoToJSON,
    SerialConnectionSettingsDtoToJSONTyped,
} from './SerialConnectionSettingsDto';
import type { TcpConnectionSettingsDto } from './TcpConnectionSettingsDto';
import {
    TcpConnectionSettingsDtoFromJSON,
    TcpConnectionSettingsDtoFromJSONTyped,
    TcpConnectionSettingsDtoToJSON,
    TcpConnectionSettingsDtoToJSONTyped,
} from './TcpConnectionSettingsDto';

/**
 * 
 * @export
 * @interface ConnectionSettingsDto
 */
export interface ConnectionSettingsDto {
    /**
     * 
     * @type {ConnectionType}
     * @memberof ConnectionSettingsDto
     */
    connectionType: ConnectionType;
    /**
     * 
     * @type {boolean}
     * @memberof ConnectionSettingsDto
     */
    autoConnectEnabled: boolean;
    /**
     * 
     * @type {SerialConnectionSettingsDto}
     * @memberof ConnectionSettingsDto
     */
    serial: SerialConnectionSettingsDto;
    /**
     * 
     * @type {TcpConnectionSettingsDto}
     * @memberof ConnectionSettingsDto
     */
    tcp: TcpConnectionSettingsDto;
}



/**
 * Check if a given object implements the ConnectionSettingsDto interface.
 */
export function instanceOfConnectionSettingsDto(value: object): value is ConnectionSettingsDto {
    if (!('connectionType' in value) || value['connectionType'] === undefined) return false;
    if (!('autoConnectEnabled' in value) || value['autoConnectEnabled'] === undefined) return false;
    if (!('serial' in value) || value['serial'] === undefined) return false;
    if (!('tcp' in value) || value['tcp'] === undefined) return false;
    return true;
}

export function ConnectionSettingsDtoFromJSON(json: any): ConnectionSettingsDto {
    return ConnectionSettingsDtoFromJSONTyped(json, false);
}

export function ConnectionSettingsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionSettingsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'connectionType': ConnectionTypeFromJSON(json['connectionType']),
        'autoConnectEnabled': json['autoConnectEnabled'],
        'serial': SerialConnectionSettingsDtoFromJSON(json['serial']),
        'tcp': TcpConnectionSettingsDtoFromJSON(json['tcp']),
    };
}

export function ConnectionSettingsDtoToJSON(json: any): ConnectionSettingsDto {
    return ConnectionSettingsDtoToJSONTyped(json, false);
}

export function ConnectionSettingsDtoToJSONTyped(value?: ConnectionSettingsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'connectionType': ConnectionTypeToJSON(value['connectionType']),
        'autoConnectEnabled': value['autoConnectEnabled'],
        'serial': SerialConnectionSettingsDtoToJSON(value['serial']),
        'tcp': TcpConnectionSettingsDtoToJSON(value['tcp']),
    };
}

