/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1.0.0-alpha.8
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-alpha.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConnectTcpDeviceRequest
 */
export interface ConnectTcpDeviceRequest {
    /**
     * 
     * @type {string}
     * @memberof ConnectTcpDeviceRequest
     */
    ipAddress: string;
    /**
     * 
     * @type {number}
     * @memberof ConnectTcpDeviceRequest
     */
    port?: number;
}

/**
 * Check if a given object implements the ConnectTcpDeviceRequest interface.
 */
export function instanceOfConnectTcpDeviceRequest(value: object): value is ConnectTcpDeviceRequest {
    if (!('ipAddress' in value) || value['ipAddress'] === undefined) return false;
    return true;
}

export function ConnectTcpDeviceRequestFromJSON(json: any): ConnectTcpDeviceRequest {
    return ConnectTcpDeviceRequestFromJSONTyped(json, false);
}

export function ConnectTcpDeviceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectTcpDeviceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'ipAddress': json['ipAddress'],
        'port': json['port'] == null ? undefined : json['port'],
    };
}

export function ConnectTcpDeviceRequestToJSON(json: any): ConnectTcpDeviceRequest {
    return ConnectTcpDeviceRequestToJSONTyped(json, false);
}

export function ConnectTcpDeviceRequestToJSONTyped(value?: ConnectTcpDeviceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ipAddress': value['ipAddress'],
        'port': value['port'],
    };
}

