/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1.0.0-alpha.8
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-alpha.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransferJobDto } from './TransferJobDto';
import {
    TransferJobDtoFromJSON,
    TransferJobDtoFromJSONTyped,
    TransferJobDtoToJSON,
    TransferJobDtoToJSONTyped,
} from './TransferJobDto';

/**
 * 
 * @export
 * @interface CreateJobResponse
 */
export interface CreateJobResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateJobResponse
     */
    jobId: string;
    /**
     * 
     * @type {TransferJobDto}
     * @memberof CreateJobResponse
     */
    job: TransferJobDto;
}

/**
 * Check if a given object implements the CreateJobResponse interface.
 */
export function instanceOfCreateJobResponse(value: object): value is CreateJobResponse {
    if (!('jobId' in value) || value['jobId'] === undefined) return false;
    if (!('job' in value) || value['job'] === undefined) return false;
    return true;
}

export function CreateJobResponseFromJSON(json: any): CreateJobResponse {
    return CreateJobResponseFromJSONTyped(json, false);
}

export function CreateJobResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateJobResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'jobId': json['jobId'],
        'job': TransferJobDtoFromJSON(json['job']),
    };
}

export function CreateJobResponseToJSON(json: any): CreateJobResponse {
    return CreateJobResponseToJSONTyped(json, false);
}

export function CreateJobResponseToJSONTyped(value?: CreateJobResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jobId': value['jobId'],
        'job': TransferJobDtoToJSON(value['job']),
    };
}

