/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1.0.0-alpha.8
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-alpha.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateJobBody
 */
export interface CreateJobBody {
    /**
     * 
     * @type {string}
     * @memberof CreateJobBody
     */
    destinationDirectory?: string;
}

/**
 * Check if a given object implements the CreateJobBody interface.
 */
export function instanceOfCreateJobBody(value: object): value is CreateJobBody {
    return true;
}

export function CreateJobBodyFromJSON(json: any): CreateJobBody {
    return CreateJobBodyFromJSONTyped(json, false);
}

export function CreateJobBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateJobBody {
    if (json == null) {
        return json;
    }
    return {
        
        'destinationDirectory': json['destinationDirectory'] == null ? undefined : json['destinationDirectory'],
    };
}

export function CreateJobBodyToJSON(json: any): CreateJobBody {
    return CreateJobBodyToJSONTyped(json, false);
}

export function CreateJobBodyToJSONTyped(value?: CreateJobBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'destinationDirectory': value['destinationDirectory'],
    };
}

