/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1.0.0-alpha.8
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-alpha.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AudioSettingsDto } from './AudioSettingsDto';
import {
    AudioSettingsDtoFromJSON,
    AudioSettingsDtoFromJSONTyped,
    AudioSettingsDtoToJSON,
    AudioSettingsDtoToJSONTyped,
} from './AudioSettingsDto';
import type { IndexingStatusDto } from './IndexingStatusDto';
import {
    IndexingStatusDtoFromJSON,
    IndexingStatusDtoFromJSONTyped,
    IndexingStatusDtoToJSON,
    IndexingStatusDtoToJSONTyped,
} from './IndexingStatusDto';
import type { VideoSettingsDto } from './VideoSettingsDto';
import {
    VideoSettingsDtoFromJSON,
    VideoSettingsDtoFromJSONTyped,
    VideoSettingsDtoToJSON,
    VideoSettingsDtoToJSONTyped,
} from './VideoSettingsDto';

/**
 * 
 * @export
 * @interface DeviceSettingsDto
 */
export interface DeviceSettingsDto {
    /**
     * 
     * @type {string}
     * @memberof DeviceSettingsDto
     */
    deviceId: string;
    /**
     * 
     * @type {VideoSettingsDto}
     * @memberof DeviceSettingsDto
     */
    videoSettings: VideoSettingsDto;
    /**
     * 
     * @type {AudioSettingsDto}
     * @memberof DeviceSettingsDto
     */
    audioSettings: AudioSettingsDto;
    /**
     * 
     * @type {IndexingStatusDto}
     * @memberof DeviceSettingsDto
     */
    indexingStatus: IndexingStatusDto;
}

/**
 * Check if a given object implements the DeviceSettingsDto interface.
 */
export function instanceOfDeviceSettingsDto(value: object): value is DeviceSettingsDto {
    if (!('deviceId' in value) || value['deviceId'] === undefined) return false;
    if (!('videoSettings' in value) || value['videoSettings'] === undefined) return false;
    if (!('audioSettings' in value) || value['audioSettings'] === undefined) return false;
    if (!('indexingStatus' in value) || value['indexingStatus'] === undefined) return false;
    return true;
}

export function DeviceSettingsDtoFromJSON(json: any): DeviceSettingsDto {
    return DeviceSettingsDtoFromJSONTyped(json, false);
}

export function DeviceSettingsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceSettingsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'deviceId': json['deviceId'],
        'videoSettings': VideoSettingsDtoFromJSON(json['videoSettings']),
        'audioSettings': AudioSettingsDtoFromJSON(json['audioSettings']),
        'indexingStatus': IndexingStatusDtoFromJSON(json['indexingStatus']),
    };
}

export function DeviceSettingsDtoToJSON(json: any): DeviceSettingsDto {
    return DeviceSettingsDtoToJSONTyped(json, false);
}

export function DeviceSettingsDtoToJSONTyped(value?: DeviceSettingsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deviceId': value['deviceId'],
        'videoSettings': VideoSettingsDtoToJSON(value['videoSettings']),
        'audioSettings': AudioSettingsDtoToJSON(value['audioSettings']),
        'indexingStatus': IndexingStatusDtoToJSON(value['indexingStatus']),
    };
}

