/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1.0.0-alpha.1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConnectionSettingsDto } from './ConnectionSettingsDto';
import {
    ConnectionSettingsDtoFromJSON,
    ConnectionSettingsDtoFromJSONTyped,
    ConnectionSettingsDtoToJSON,
    ConnectionSettingsDtoToJSONTyped,
} from './ConnectionSettingsDto';
import type { VideoSettingsDto } from './VideoSettingsDto';
import {
    VideoSettingsDtoFromJSON,
    VideoSettingsDtoFromJSONTyped,
    VideoSettingsDtoToJSON,
    VideoSettingsDtoToJSONTyped,
} from './VideoSettingsDto';

/**
 * 
 * @export
 * @interface DeviceSettingsDto
 */
export interface DeviceSettingsDto {
    /**
     * 
     * @type {string}
     * @memberof DeviceSettingsDto
     */
    deviceId: string;
    /**
     * 
     * @type {VideoSettingsDto}
     * @memberof DeviceSettingsDto
     */
    videoSettings: VideoSettingsDto;
    /**
     * 
     * @type {ConnectionSettingsDto}
     * @memberof DeviceSettingsDto
     */
    connectionSettings: ConnectionSettingsDto;
}

/**
 * Check if a given object implements the DeviceSettingsDto interface.
 */
export function instanceOfDeviceSettingsDto(value: object): value is DeviceSettingsDto {
    if (!('deviceId' in value) || value['deviceId'] === undefined) return false;
    if (!('videoSettings' in value) || value['videoSettings'] === undefined) return false;
    if (!('connectionSettings' in value) || value['connectionSettings'] === undefined) return false;
    return true;
}

export function DeviceSettingsDtoFromJSON(json: any): DeviceSettingsDto {
    return DeviceSettingsDtoFromJSONTyped(json, false);
}

export function DeviceSettingsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceSettingsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'deviceId': json['deviceId'],
        'videoSettings': VideoSettingsDtoFromJSON(json['videoSettings']),
        'connectionSettings': ConnectionSettingsDtoFromJSON(json['connectionSettings']),
    };
}

export function DeviceSettingsDtoToJSON(json: any): DeviceSettingsDto {
    return DeviceSettingsDtoToJSONTyped(json, false);
}

export function DeviceSettingsDtoToJSONTyped(value?: DeviceSettingsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deviceId': value['deviceId'],
        'videoSettings': VideoSettingsDtoToJSON(value['videoSettings']),
        'connectionSettings': ConnectionSettingsDtoToJSON(value['connectionSettings']),
    };
}

