/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileTransferSettingsDto
 */
export interface FileTransferSettingsDto {
    /**
     * 
     * @type {string}
     * @memberof FileTransferSettingsDto
     */
    watchDirectoryLocation: string;
    /**
     * 
     * @type {string}
     * @memberof FileTransferSettingsDto
     */
    autoTransferPath: string;
    /**
     * 
     * @type {boolean}
     * @memberof FileTransferSettingsDto
     */
    autoFileCopyEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FileTransferSettingsDto
     */
    autoLaunchOnCopyEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FileTransferSettingsDto
     */
    navToDirOnLaunch: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FileTransferSettingsDto
     */
    syncFilesEnabled: boolean;
}

/**
 * Check if a given object implements the FileTransferSettingsDto interface.
 */
export function instanceOfFileTransferSettingsDto(value: object): value is FileTransferSettingsDto {
    if (!('watchDirectoryLocation' in value) || value['watchDirectoryLocation'] === undefined) return false;
    if (!('autoTransferPath' in value) || value['autoTransferPath'] === undefined) return false;
    if (!('autoFileCopyEnabled' in value) || value['autoFileCopyEnabled'] === undefined) return false;
    if (!('autoLaunchOnCopyEnabled' in value) || value['autoLaunchOnCopyEnabled'] === undefined) return false;
    if (!('navToDirOnLaunch' in value) || value['navToDirOnLaunch'] === undefined) return false;
    if (!('syncFilesEnabled' in value) || value['syncFilesEnabled'] === undefined) return false;
    return true;
}

export function FileTransferSettingsDtoFromJSON(json: any): FileTransferSettingsDto {
    return FileTransferSettingsDtoFromJSONTyped(json, false);
}

export function FileTransferSettingsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileTransferSettingsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'watchDirectoryLocation': json['watchDirectoryLocation'],
        'autoTransferPath': json['autoTransferPath'],
        'autoFileCopyEnabled': json['autoFileCopyEnabled'],
        'autoLaunchOnCopyEnabled': json['autoLaunchOnCopyEnabled'],
        'navToDirOnLaunch': json['navToDirOnLaunch'],
        'syncFilesEnabled': json['syncFilesEnabled'],
    };
}

export function FileTransferSettingsDtoToJSON(json: any): FileTransferSettingsDto {
    return FileTransferSettingsDtoToJSONTyped(json, false);
}

export function FileTransferSettingsDtoToJSONTyped(value?: FileTransferSettingsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'watchDirectoryLocation': value['watchDirectoryLocation'],
        'autoTransferPath': value['autoTransferPath'],
        'autoFileCopyEnabled': value['autoFileCopyEnabled'],
        'autoLaunchOnCopyEnabled': value['autoLaunchOnCopyEnabled'],
        'navToDirOnLaunch': value['navToDirOnLaunch'],
        'syncFilesEnabled': value['syncFilesEnabled'],
    };
}

