/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1.0.0-alpha.8
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-alpha.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransferJobDto2 } from './TransferJobDto2';
import {
    TransferJobDto2FromJSON,
    TransferJobDto2FromJSONTyped,
    TransferJobDto2ToJSON,
    TransferJobDto2ToJSONTyped,
} from './TransferJobDto2';

/**
 * 
 * @export
 * @interface GetActiveJobResponse
 */
export interface GetActiveJobResponse {
    /**
     * 
     * @type {TransferJobDto2}
     * @memberof GetActiveJobResponse
     */
    job?: TransferJobDto2 | null;
}

/**
 * Check if a given object implements the GetActiveJobResponse interface.
 */
export function instanceOfGetActiveJobResponse(value: object): value is GetActiveJobResponse {
    return true;
}

export function GetActiveJobResponseFromJSON(json: any): GetActiveJobResponse {
    return GetActiveJobResponseFromJSONTyped(json, false);
}

export function GetActiveJobResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetActiveJobResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'job': json['job'] === undefined ? undefined : json['job'] === null ? null : TransferJobDto2FromJSON(json['job']),
    };
}

export function GetActiveJobResponseToJSON(json: any): GetActiveJobResponse {
    return GetActiveJobResponseToJSONTyped(json, false);
}

export function GetActiveJobResponseToJSONTyped(value?: GetActiveJobResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'job': TransferJobDto2ToJSON(value['job']),
    };
}

