/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1.0.0-alpha.8
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-alpha.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransferJobDto } from './TransferJobDto';
import {
    TransferJobDtoFromJSON,
    TransferJobDtoFromJSONTyped,
    TransferJobDtoToJSON,
    TransferJobDtoToJSONTyped,
} from './TransferJobDto';

/**
 * 
 * @export
 * @interface GetJobResponse
 */
export interface GetJobResponse {
    /**
     * 
     * @type {TransferJobDto}
     * @memberof GetJobResponse
     */
    job: TransferJobDto;
}

/**
 * Check if a given object implements the GetJobResponse interface.
 */
export function instanceOfGetJobResponse(value: object): value is GetJobResponse {
    if (!('job' in value) || value['job'] === undefined) return false;
    return true;
}

export function GetJobResponseFromJSON(json: any): GetJobResponse {
    return GetJobResponseFromJSONTyped(json, false);
}

export function GetJobResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetJobResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'job': TransferJobDtoFromJSON(json['job']),
    };
}

export function GetJobResponseToJSON(json: any): GetJobResponse {
    return GetJobResponseToJSONTyped(json, false);
}

export function GetJobResponseToJSONTyped(value?: GetJobResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'job': TransferJobDtoToJSON(value['job']),
    };
}

