/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppSettingsDto } from './AppSettingsDto';
import {
    AppSettingsDtoFromJSON,
    AppSettingsDtoFromJSONTyped,
    AppSettingsDtoToJSON,
    AppSettingsDtoToJSONTyped,
} from './AppSettingsDto';
import type { PlayerSettingsDto } from './PlayerSettingsDto';
import {
    PlayerSettingsDtoFromJSON,
    PlayerSettingsDtoFromJSONTyped,
    PlayerSettingsDtoToJSON,
    PlayerSettingsDtoToJSONTyped,
} from './PlayerSettingsDto';
import type { FileTransferSettingsDto } from './FileTransferSettingsDto';
import {
    FileTransferSettingsDtoFromJSON,
    FileTransferSettingsDtoFromJSONTyped,
    FileTransferSettingsDtoToJSON,
    FileTransferSettingsDtoToJSONTyped,
} from './FileTransferSettingsDto';
import type { SearchSettingsDto } from './SearchSettingsDto';
import {
    SearchSettingsDtoFromJSON,
    SearchSettingsDtoFromJSONTyped,
    SearchSettingsDtoToJSON,
    SearchSettingsDtoToJSONTyped,
} from './SearchSettingsDto';

/**
 * 
 * @export
 * @interface GetSettingsResponse
 */
export interface GetSettingsResponse {
    /**
     * 
     * @type {PlayerSettingsDto}
     * @memberof GetSettingsResponse
     */
    playerSettings: PlayerSettingsDto;
    /**
     * 
     * @type {FileTransferSettingsDto}
     * @memberof GetSettingsResponse
     */
    fileTransferSettings: FileTransferSettingsDto;
    /**
     * 
     * @type {SearchSettingsDto}
     * @memberof GetSettingsResponse
     */
    searchSettings: SearchSettingsDto;
    /**
     * 
     * @type {AppSettingsDto}
     * @memberof GetSettingsResponse
     */
    appSettings: AppSettingsDto;
}

/**
 * Check if a given object implements the GetSettingsResponse interface.
 */
export function instanceOfGetSettingsResponse(value: object): value is GetSettingsResponse {
    if (!('playerSettings' in value) || value['playerSettings'] === undefined) return false;
    if (!('fileTransferSettings' in value) || value['fileTransferSettings'] === undefined) return false;
    if (!('searchSettings' in value) || value['searchSettings'] === undefined) return false;
    if (!('appSettings' in value) || value['appSettings'] === undefined) return false;
    return true;
}

export function GetSettingsResponseFromJSON(json: any): GetSettingsResponse {
    return GetSettingsResponseFromJSONTyped(json, false);
}

export function GetSettingsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSettingsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'playerSettings': PlayerSettingsDtoFromJSON(json['playerSettings']),
        'fileTransferSettings': FileTransferSettingsDtoFromJSON(json['fileTransferSettings']),
        'searchSettings': SearchSettingsDtoFromJSON(json['searchSettings']),
        'appSettings': AppSettingsDtoFromJSON(json['appSettings']),
    };
}

export function GetSettingsResponseToJSON(json: any): GetSettingsResponse {
    return GetSettingsResponseToJSONTyped(json, false);
}

export function GetSettingsResponseToJSONTyped(value?: GetSettingsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'playerSettings': PlayerSettingsDtoToJSON(value['playerSettings']),
        'fileTransferSettings': FileTransferSettingsDtoToJSON(value['fileTransferSettings']),
        'searchSettings': SearchSettingsDtoToJSON(value['searchSettings']),
        'appSettings': AppSettingsDtoToJSON(value['appSettings']),
    };
}

