/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1.0.0-alpha.7
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-alpha.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetVersionResponse
 */
export interface GetVersionResponse {
    /**
     * 
     * @type {string}
     * @memberof GetVersionResponse
     */
    version: string;
}

/**
 * Check if a given object implements the GetVersionResponse interface.
 */
export function instanceOfGetVersionResponse(value: object): value is GetVersionResponse {
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function GetVersionResponseFromJSON(json: any): GetVersionResponse {
    return GetVersionResponseFromJSONTyped(json, false);
}

export function GetVersionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetVersionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'],
    };
}

export function GetVersionResponseToJSON(json: any): GetVersionResponse {
    return GetVersionResponseToJSONTyped(json, false);
}

export function GetVersionResponseToJSONTyped(value?: GetVersionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
    };
}

