/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1.0.0-alpha.8
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-alpha.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const HardwareVariant = {
    Unknown: 'Unknown',
    TeensyRom: 'TeensyRom',
    TeensyRomPlus: 'TeensyRomPlus'
} as const;
export type HardwareVariant = typeof HardwareVariant[keyof typeof HardwareVariant];


export function instanceOfHardwareVariant(value: any): boolean {
    for (const key in HardwareVariant) {
        if (Object.prototype.hasOwnProperty.call(HardwareVariant, key)) {
            if (HardwareVariant[key as keyof typeof HardwareVariant] === value) {
                return true;
            }
        }
    }
    return false;
}

export function HardwareVariantFromJSON(json: any): HardwareVariant {
    return HardwareVariantFromJSONTyped(json, false);
}

export function HardwareVariantFromJSONTyped(json: any, ignoreDiscriminator: boolean): HardwareVariant {
    return json as HardwareVariant;
}

export function HardwareVariantToJSON(value?: HardwareVariant | null): any {
    return value as any;
}

export function HardwareVariantToJSONTyped(value: any, ignoreDiscriminator: boolean): HardwareVariant {
    return value as HardwareVariant;
}

