/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1.0.0-alpha.7
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-alpha.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IndexingStatusDto
 */
export interface IndexingStatusDto {
    /**
     * 
     * @type {Date}
     * @memberof IndexingStatusDto
     */
    sdLastIndexed?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof IndexingStatusDto
     */
    usbLastIndexed?: Date | null;
}

/**
 * Check if a given object implements the IndexingStatusDto interface.
 */
export function instanceOfIndexingStatusDto(value: object): value is IndexingStatusDto {
    return true;
}

export function IndexingStatusDtoFromJSON(json: any): IndexingStatusDto {
    return IndexingStatusDtoFromJSONTyped(json, false);
}

export function IndexingStatusDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndexingStatusDto {
    if (json == null) {
        return json;
    }
    return {
        
        'sdLastIndexed': json['sdLastIndexed'] == null ? undefined : (new Date(json['sdLastIndexed'])),
        'usbLastIndexed': json['usbLastIndexed'] == null ? undefined : (new Date(json['usbLastIndexed'])),
    };
}

export function IndexingStatusDtoToJSON(json: any): IndexingStatusDto {
    return IndexingStatusDtoToJSONTyped(json, false);
}

export function IndexingStatusDtoToJSONTyped(value?: IndexingStatusDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sdLastIndexed': value['sdLastIndexed'] == null ? undefined : ((value['sdLastIndexed'] as any).toISOString()),
        'usbLastIndexed': value['usbLastIndexed'] == null ? undefined : ((value['usbLastIndexed'] as any).toISOString()),
    };
}

