/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1.0.0-alpha.8
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-alpha.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MachineType = {
    Unknown: 'Unknown',
    C64: 'C64',
    C128: 'C128'
} as const;
export type MachineType = typeof MachineType[keyof typeof MachineType];


export function instanceOfMachineType(value: any): boolean {
    for (const key in MachineType) {
        if (Object.prototype.hasOwnProperty.call(MachineType, key)) {
            if (MachineType[key as keyof typeof MachineType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MachineTypeFromJSON(json: any): MachineType {
    return MachineTypeFromJSONTyped(json, false);
}

export function MachineTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MachineType {
    return json as MachineType;
}

export function MachineTypeToJSON(value?: MachineType | null): any {
    return value as any;
}

export function MachineTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): MachineType {
    return value as MachineType;
}

