/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1.0.0-alpha.7
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-alpha.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TeensyFilterType } from './TeensyFilterType';
import {
    TeensyFilterTypeFromJSON,
    TeensyFilterTypeFromJSONTyped,
    TeensyFilterTypeToJSON,
    TeensyFilterTypeToJSONTyped,
} from './TeensyFilterType';

/**
 * 
 * @export
 * @interface PlayerSettingsDto
 */
export interface PlayerSettingsDto {
    /**
     * 
     * @type {boolean}
     * @memberof PlayerSettingsDto
     */
    repeatModeOnStartup: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PlayerSettingsDto
     */
    playTimerEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PlayerSettingsDto
     */
    muteFastForward: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PlayerSettingsDto
     */
    muteRandomSeek: boolean;
    /**
     * 
     * @type {TeensyFilterType}
     * @memberof PlayerSettingsDto
     */
    startupFilter: TeensyFilterType;
    /**
     * 
     * @type {boolean}
     * @memberof PlayerSettingsDto
     */
    startupLaunchEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PlayerSettingsDto
     */
    startupLaunchRandom: boolean;
}



/**
 * Check if a given object implements the PlayerSettingsDto interface.
 */
export function instanceOfPlayerSettingsDto(value: object): value is PlayerSettingsDto {
    if (!('repeatModeOnStartup' in value) || value['repeatModeOnStartup'] === undefined) return false;
    if (!('playTimerEnabled' in value) || value['playTimerEnabled'] === undefined) return false;
    if (!('muteFastForward' in value) || value['muteFastForward'] === undefined) return false;
    if (!('muteRandomSeek' in value) || value['muteRandomSeek'] === undefined) return false;
    if (!('startupFilter' in value) || value['startupFilter'] === undefined) return false;
    if (!('startupLaunchEnabled' in value) || value['startupLaunchEnabled'] === undefined) return false;
    if (!('startupLaunchRandom' in value) || value['startupLaunchRandom'] === undefined) return false;
    return true;
}

export function PlayerSettingsDtoFromJSON(json: any): PlayerSettingsDto {
    return PlayerSettingsDtoFromJSONTyped(json, false);
}

export function PlayerSettingsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerSettingsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'repeatModeOnStartup': json['repeatModeOnStartup'],
        'playTimerEnabled': json['playTimerEnabled'],
        'muteFastForward': json['muteFastForward'],
        'muteRandomSeek': json['muteRandomSeek'],
        'startupFilter': TeensyFilterTypeFromJSON(json['startupFilter']),
        'startupLaunchEnabled': json['startupLaunchEnabled'],
        'startupLaunchRandom': json['startupLaunchRandom'],
    };
}

export function PlayerSettingsDtoToJSON(json: any): PlayerSettingsDto {
    return PlayerSettingsDtoToJSONTyped(json, false);
}

export function PlayerSettingsDtoToJSONTyped(value?: PlayerSettingsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'repeatModeOnStartup': value['repeatModeOnStartup'],
        'playTimerEnabled': value['playTimerEnabled'],
        'muteFastForward': value['muteFastForward'],
        'muteRandomSeek': value['muteRandomSeek'],
        'startupFilter': TeensyFilterTypeToJSON(value['startupFilter']),
        'startupLaunchEnabled': value['startupLaunchEnabled'],
        'startupLaunchRandom': value['startupLaunchRandom'],
    };
}

