/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppSettingsDto } from './AppSettingsDto';
import {
    AppSettingsDtoFromJSON,
    AppSettingsDtoFromJSONTyped,
    AppSettingsDtoToJSON,
    AppSettingsDtoToJSONTyped,
} from './AppSettingsDto';
import type { ConnectionSettingsDto } from './ConnectionSettingsDto';
import {
    ConnectionSettingsDtoFromJSON,
    ConnectionSettingsDtoFromJSONTyped,
    ConnectionSettingsDtoToJSON,
    ConnectionSettingsDtoToJSONTyped,
} from './ConnectionSettingsDto';
import type { PlayerSettingsDto } from './PlayerSettingsDto';
import {
    PlayerSettingsDtoFromJSON,
    PlayerSettingsDtoFromJSONTyped,
    PlayerSettingsDtoToJSON,
    PlayerSettingsDtoToJSONTyped,
} from './PlayerSettingsDto';
import type { VideoSettingsDto } from './VideoSettingsDto';
import {
    VideoSettingsDtoFromJSON,
    VideoSettingsDtoFromJSONTyped,
    VideoSettingsDtoToJSON,
    VideoSettingsDtoToJSONTyped,
} from './VideoSettingsDto';
import type { FileTransferSettingsDto } from './FileTransferSettingsDto';
import {
    FileTransferSettingsDtoFromJSON,
    FileTransferSettingsDtoFromJSONTyped,
    FileTransferSettingsDtoToJSON,
    FileTransferSettingsDtoToJSONTyped,
} from './FileTransferSettingsDto';
import type { SearchSettingsDto } from './SearchSettingsDto';
import {
    SearchSettingsDtoFromJSON,
    SearchSettingsDtoFromJSONTyped,
    SearchSettingsDtoToJSON,
    SearchSettingsDtoToJSONTyped,
} from './SearchSettingsDto';

/**
 * 
 * @export
 * @interface SaveSettingsRequest
 */
export interface SaveSettingsRequest {
    /**
     * 
     * @type {ConnectionSettingsDto}
     * @memberof SaveSettingsRequest
     */
    connectionSettings: ConnectionSettingsDto;
    /**
     * 
     * @type {PlayerSettingsDto}
     * @memberof SaveSettingsRequest
     */
    playerSettings: PlayerSettingsDto;
    /**
     * 
     * @type {VideoSettingsDto}
     * @memberof SaveSettingsRequest
     */
    videoSettings: VideoSettingsDto;
    /**
     * 
     * @type {FileTransferSettingsDto}
     * @memberof SaveSettingsRequest
     */
    fileTransferSettings: FileTransferSettingsDto;
    /**
     * 
     * @type {SearchSettingsDto}
     * @memberof SaveSettingsRequest
     */
    searchSettings: SearchSettingsDto;
    /**
     * 
     * @type {AppSettingsDto}
     * @memberof SaveSettingsRequest
     */
    appSettings: AppSettingsDto;
}

/**
 * Check if a given object implements the SaveSettingsRequest interface.
 */
export function instanceOfSaveSettingsRequest(value: object): value is SaveSettingsRequest {
    if (!('connectionSettings' in value) || value['connectionSettings'] === undefined) return false;
    if (!('playerSettings' in value) || value['playerSettings'] === undefined) return false;
    if (!('videoSettings' in value) || value['videoSettings'] === undefined) return false;
    if (!('fileTransferSettings' in value) || value['fileTransferSettings'] === undefined) return false;
    if (!('searchSettings' in value) || value['searchSettings'] === undefined) return false;
    if (!('appSettings' in value) || value['appSettings'] === undefined) return false;
    return true;
}

export function SaveSettingsRequestFromJSON(json: any): SaveSettingsRequest {
    return SaveSettingsRequestFromJSONTyped(json, false);
}

export function SaveSettingsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveSettingsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'connectionSettings': ConnectionSettingsDtoFromJSON(json['connectionSettings']),
        'playerSettings': PlayerSettingsDtoFromJSON(json['playerSettings']),
        'videoSettings': VideoSettingsDtoFromJSON(json['videoSettings']),
        'fileTransferSettings': FileTransferSettingsDtoFromJSON(json['fileTransferSettings']),
        'searchSettings': SearchSettingsDtoFromJSON(json['searchSettings']),
        'appSettings': AppSettingsDtoFromJSON(json['appSettings']),
    };
}

export function SaveSettingsRequestToJSON(json: any): SaveSettingsRequest {
    return SaveSettingsRequestToJSONTyped(json, false);
}

export function SaveSettingsRequestToJSONTyped(value?: SaveSettingsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'connectionSettings': ConnectionSettingsDtoToJSON(value['connectionSettings']),
        'playerSettings': PlayerSettingsDtoToJSON(value['playerSettings']),
        'videoSettings': VideoSettingsDtoToJSON(value['videoSettings']),
        'fileTransferSettings': FileTransferSettingsDtoToJSON(value['fileTransferSettings']),
        'searchSettings': SearchSettingsDtoToJSON(value['searchSettings']),
        'appSettings': AppSettingsDtoToJSON(value['appSettings']),
    };
}

