/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1.0.0-alpha.7
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-alpha.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaveSettingsResponse
 */
export interface SaveSettingsResponse {
    /**
     * 
     * @type {string}
     * @memberof SaveSettingsResponse
     */
    message: string;
}

/**
 * Check if a given object implements the SaveSettingsResponse interface.
 */
export function instanceOfSaveSettingsResponse(value: object): value is SaveSettingsResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function SaveSettingsResponseFromJSON(json: any): SaveSettingsResponse {
    return SaveSettingsResponseFromJSONTyped(json, false);
}

export function SaveSettingsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveSettingsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function SaveSettingsResponseToJSON(json: any): SaveSettingsResponse {
    return SaveSettingsResponseToJSONTyped(json, false);
}

export function SaveSettingsResponseToJSONTyped(value?: SaveSettingsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

