/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1.0.0-alpha.8
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-alpha.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransferJobDto } from './TransferJobDto';
import {
    TransferJobDtoFromJSON,
    TransferJobDtoFromJSONTyped,
    TransferJobDtoToJSON,
    TransferJobDtoToJSONTyped,
} from './TransferJobDto';

/**
 * 
 * @export
 * @interface SealJobResponse
 */
export interface SealJobResponse {
    /**
     * 
     * @type {TransferJobDto}
     * @memberof SealJobResponse
     */
    job: TransferJobDto;
}

/**
 * Check if a given object implements the SealJobResponse interface.
 */
export function instanceOfSealJobResponse(value: object): value is SealJobResponse {
    if (!('job' in value) || value['job'] === undefined) return false;
    return true;
}

export function SealJobResponseFromJSON(json: any): SealJobResponse {
    return SealJobResponseFromJSONTyped(json, false);
}

export function SealJobResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SealJobResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'job': TransferJobDtoFromJSON(json['job']),
    };
}

export function SealJobResponseToJSON(json: any): SealJobResponse {
    return SealJobResponseToJSONTyped(json, false);
}

export function SealJobResponseToJSONTyped(value?: SealJobResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'job': TransferJobDtoToJSON(value['job']),
    };
}

