/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1.0.0-alpha.8
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-alpha.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchWeightsDto
 */
export interface SearchWeightsDto {
    /**
     * 
     * @type {number}
     * @memberof SearchWeightsDto
     */
    title: number;
    /**
     * 
     * @type {number}
     * @memberof SearchWeightsDto
     */
    fileName: number;
    /**
     * 
     * @type {number}
     * @memberof SearchWeightsDto
     */
    filePath: number;
    /**
     * 
     * @type {number}
     * @memberof SearchWeightsDto
     */
    creator: number;
    /**
     * 
     * @type {number}
     * @memberof SearchWeightsDto
     */
    description: number;
}

/**
 * Check if a given object implements the SearchWeightsDto interface.
 */
export function instanceOfSearchWeightsDto(value: object): value is SearchWeightsDto {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('fileName' in value) || value['fileName'] === undefined) return false;
    if (!('filePath' in value) || value['filePath'] === undefined) return false;
    if (!('creator' in value) || value['creator'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function SearchWeightsDtoFromJSON(json: any): SearchWeightsDto {
    return SearchWeightsDtoFromJSONTyped(json, false);
}

export function SearchWeightsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchWeightsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'fileName': json['fileName'],
        'filePath': json['filePath'],
        'creator': json['creator'],
        'description': json['description'],
    };
}

export function SearchWeightsDtoToJSON(json: any): SearchWeightsDto {
    return SearchWeightsDtoToJSONTyped(json, false);
}

export function SearchWeightsDtoToJSONTyped(value?: SearchWeightsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'fileName': value['fileName'],
        'filePath': value['filePath'],
        'creator': value['creator'],
        'description': value['description'],
    };
}

