/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchWeightsDto } from './SearchWeightsDto';
import {
    SearchWeightsDtoFromJSON,
    SearchWeightsDtoFromJSONTyped,
    SearchWeightsDtoToJSON,
    SearchWeightsDtoToJSONTyped,
} from './SearchWeightsDto';

/**
 * 
 * @export
 * @interface SearchSettingsDto
 */
export interface SearchSettingsDto {
    /**
     * 
     * @type {SearchWeightsDto}
     * @memberof SearchSettingsDto
     */
    searchWeights: SearchWeightsDto;
    /**
     * 
     * @type {Array<string>}
     * @memberof SearchSettingsDto
     */
    searchStopWords: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SearchSettingsDto
     */
    bannedDirectories: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SearchSettingsDto
     */
    bannedFiles: Array<string>;
}

/**
 * Check if a given object implements the SearchSettingsDto interface.
 */
export function instanceOfSearchSettingsDto(value: object): value is SearchSettingsDto {
    if (!('searchWeights' in value) || value['searchWeights'] === undefined) return false;
    if (!('searchStopWords' in value) || value['searchStopWords'] === undefined) return false;
    if (!('bannedDirectories' in value) || value['bannedDirectories'] === undefined) return false;
    if (!('bannedFiles' in value) || value['bannedFiles'] === undefined) return false;
    return true;
}

export function SearchSettingsDtoFromJSON(json: any): SearchSettingsDto {
    return SearchSettingsDtoFromJSONTyped(json, false);
}

export function SearchSettingsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchSettingsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'searchWeights': SearchWeightsDtoFromJSON(json['searchWeights']),
        'searchStopWords': json['searchStopWords'],
        'bannedDirectories': json['bannedDirectories'],
        'bannedFiles': json['bannedFiles'],
    };
}

export function SearchSettingsDtoToJSON(json: any): SearchSettingsDto {
    return SearchSettingsDtoToJSONTyped(json, false);
}

export function SearchSettingsDtoToJSONTyped(value?: SearchSettingsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'searchWeights': SearchWeightsDtoToJSON(value['searchWeights']),
        'searchStopWords': value['searchStopWords'],
        'bannedDirectories': value['bannedDirectories'],
        'bannedFiles': value['bannedFiles'],
    };
}

