/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SerialConnectionSettingsDto
 */
export interface SerialConnectionSettingsDto {
    /**
     * 
     * @type {string}
     * @memberof SerialConnectionSettingsDto
     */
    port: string;
    /**
     * 
     * @type {number}
     * @memberof SerialConnectionSettingsDto
     */
    baudRate: number;
}

/**
 * Check if a given object implements the SerialConnectionSettingsDto interface.
 */
export function instanceOfSerialConnectionSettingsDto(value: object): value is SerialConnectionSettingsDto {
    if (!('port' in value) || value['port'] === undefined) return false;
    if (!('baudRate' in value) || value['baudRate'] === undefined) return false;
    return true;
}

export function SerialConnectionSettingsDtoFromJSON(json: any): SerialConnectionSettingsDto {
    return SerialConnectionSettingsDtoFromJSONTyped(json, false);
}

export function SerialConnectionSettingsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SerialConnectionSettingsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'port': json['port'],
        'baudRate': json['baudRate'],
    };
}

export function SerialConnectionSettingsDtoToJSON(json: any): SerialConnectionSettingsDto {
    return SerialConnectionSettingsDtoToJSONTyped(json, false);
}

export function SerialConnectionSettingsDtoToJSONTyped(value?: SerialConnectionSettingsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'port': value['port'],
        'baudRate': value['baudRate'],
    };
}

