/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TcpConnectionSettingsDto
 */
export interface TcpConnectionSettingsDto {
    /**
     * 
     * @type {string}
     * @memberof TcpConnectionSettingsDto
     */
    hostAddress: string;
    /**
     * 
     * @type {number}
     * @memberof TcpConnectionSettingsDto
     */
    port: number;
    /**
     * 
     * @type {number}
     * @memberof TcpConnectionSettingsDto
     */
    connectionTimeoutMs: number;
    /**
     * 
     * @type {number}
     * @memberof TcpConnectionSettingsDto
     */
    readTimeoutMs: number;
    /**
     * 
     * @type {number}
     * @memberof TcpConnectionSettingsDto
     */
    writeTimeoutMs: number;
}

/**
 * Check if a given object implements the TcpConnectionSettingsDto interface.
 */
export function instanceOfTcpConnectionSettingsDto(value: object): value is TcpConnectionSettingsDto {
    if (!('hostAddress' in value) || value['hostAddress'] === undefined) return false;
    if (!('port' in value) || value['port'] === undefined) return false;
    if (!('connectionTimeoutMs' in value) || value['connectionTimeoutMs'] === undefined) return false;
    if (!('readTimeoutMs' in value) || value['readTimeoutMs'] === undefined) return false;
    if (!('writeTimeoutMs' in value) || value['writeTimeoutMs'] === undefined) return false;
    return true;
}

export function TcpConnectionSettingsDtoFromJSON(json: any): TcpConnectionSettingsDto {
    return TcpConnectionSettingsDtoFromJSONTyped(json, false);
}

export function TcpConnectionSettingsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TcpConnectionSettingsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'hostAddress': json['hostAddress'],
        'port': json['port'],
        'connectionTimeoutMs': json['connectionTimeoutMs'],
        'readTimeoutMs': json['readTimeoutMs'],
        'writeTimeoutMs': json['writeTimeoutMs'],
    };
}

export function TcpConnectionSettingsDtoToJSON(json: any): TcpConnectionSettingsDto {
    return TcpConnectionSettingsDtoToJSONTyped(json, false);
}

export function TcpConnectionSettingsDtoToJSONTyped(value?: TcpConnectionSettingsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hostAddress': value['hostAddress'],
        'port': value['port'],
        'connectionTimeoutMs': value['connectionTimeoutMs'],
        'readTimeoutMs': value['readTimeoutMs'],
        'writeTimeoutMs': value['writeTimeoutMs'],
    };
}

