/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1.0.0-alpha.1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TeensyFilterType = {
    All: 'All',
    Games: 'Games',
    Music: 'Music',
    Hex: 'Hex',
    Images: 'Images'
} as const;
export type TeensyFilterType = typeof TeensyFilterType[keyof typeof TeensyFilterType];


export function instanceOfTeensyFilterType(value: any): boolean {
    for (const key in TeensyFilterType) {
        if (Object.prototype.hasOwnProperty.call(TeensyFilterType, key)) {
            if (TeensyFilterType[key as keyof typeof TeensyFilterType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TeensyFilterTypeFromJSON(json: any): TeensyFilterType {
    return TeensyFilterTypeFromJSONTyped(json, false);
}

export function TeensyFilterTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeensyFilterType {
    return json as TeensyFilterType;
}

export function TeensyFilterTypeToJSON(value?: TeensyFilterType | null): any {
    return value as any;
}

export function TeensyFilterTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): TeensyFilterType {
    return value as TeensyFilterType;
}

