/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1.0.0-alpha.8
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-alpha.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TeensyStorageType } from './TeensyStorageType';
import {
    TeensyStorageTypeFromJSON,
    TeensyStorageTypeFromJSONTyped,
    TeensyStorageTypeToJSON,
    TeensyStorageTypeToJSONTyped,
} from './TeensyStorageType';
import type { TransferJobState } from './TransferJobState';
import {
    TransferJobStateFromJSON,
    TransferJobStateFromJSONTyped,
    TransferJobStateToJSON,
    TransferJobStateToJSONTyped,
} from './TransferJobState';
import type { TransferFileCompleted } from './TransferFileCompleted';
import {
    TransferFileCompletedFromJSON,
    TransferFileCompletedFromJSONTyped,
    TransferFileCompletedToJSON,
    TransferFileCompletedToJSONTyped,
} from './TransferFileCompleted';

/**
 * 
 * @export
 * @interface TransferJobDto
 */
export interface TransferJobDto {
    /**
     * 
     * @type {string}
     * @memberof TransferJobDto
     */
    jobId: string;
    /**
     * 
     * @type {string}
     * @memberof TransferJobDto
     */
    deviceId: string;
    /**
     * 
     * @type {TeensyStorageType}
     * @memberof TransferJobDto
     */
    storageType: TeensyStorageType;
    /**
     * 
     * @type {string}
     * @memberof TransferJobDto
     */
    destinationDirectory: string;
    /**
     * 
     * @type {TransferJobState}
     * @memberof TransferJobDto
     */
    state: TransferJobState;
    /**
     * 
     * @type {number}
     * @memberof TransferJobDto
     */
    filesReceived: number;
    /**
     * 
     * @type {number}
     * @memberof TransferJobDto
     */
    filesSent: number;
    /**
     * 
     * @type {number}
     * @memberof TransferJobDto
     */
    filesFailed: number;
    /**
     * 
     * @type {number}
     * @memberof TransferJobDto
     */
    bytesSent: number;
    /**
     * 
     * @type {number}
     * @memberof TransferJobDto
     */
    totalFiles?: number | null;
    /**
     * 
     * @type {string}
     * @memberof TransferJobDto
     */
    currentFile?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof TransferJobDto
     */
    startedUtc: Date;
    /**
     * 
     * @type {Date}
     * @memberof TransferJobDto
     */
    lastActivityUtc: Date;
    /**
     * 
     * @type {string}
     * @memberof TransferJobDto
     */
    error?: string | null;
    /**
     * 
     * @type {Array<TransferFileCompleted>}
     * @memberof TransferJobDto
     */
    failures: Array<TransferFileCompleted>;
    /**
     * 
     * @type {Array<TransferFileCompleted>}
     * @memberof TransferJobDto
     */
    recentCompletions: Array<TransferFileCompleted>;
    /**
     * 
     * @type {number}
     * @memberof TransferJobDto
     */
    bytesPerSecond: number;
    /**
     * 
     * @type {number}
     * @memberof TransferJobDto
     */
    filesPerSecond: number;
    /**
     * 
     * @type {string}
     * @memberof TransferJobDto
     */
    expandingArchive?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TransferJobDto
     */
    expansionBytesWritten: number;
    /**
     * 
     * @type {number}
     * @memberof TransferJobDto
     */
    expansionBytesDeclared: number;
    /**
     * 
     * @type {number}
     * @memberof TransferJobDto
     */
    expandedFileCount?: number | null;
}



/**
 * Check if a given object implements the TransferJobDto interface.
 */
export function instanceOfTransferJobDto(value: object): value is TransferJobDto {
    if (!('jobId' in value) || value['jobId'] === undefined) return false;
    if (!('deviceId' in value) || value['deviceId'] === undefined) return false;
    if (!('storageType' in value) || value['storageType'] === undefined) return false;
    if (!('destinationDirectory' in value) || value['destinationDirectory'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('filesReceived' in value) || value['filesReceived'] === undefined) return false;
    if (!('filesSent' in value) || value['filesSent'] === undefined) return false;
    if (!('filesFailed' in value) || value['filesFailed'] === undefined) return false;
    if (!('bytesSent' in value) || value['bytesSent'] === undefined) return false;
    if (!('startedUtc' in value) || value['startedUtc'] === undefined) return false;
    if (!('lastActivityUtc' in value) || value['lastActivityUtc'] === undefined) return false;
    if (!('failures' in value) || value['failures'] === undefined) return false;
    if (!('recentCompletions' in value) || value['recentCompletions'] === undefined) return false;
    if (!('bytesPerSecond' in value) || value['bytesPerSecond'] === undefined) return false;
    if (!('filesPerSecond' in value) || value['filesPerSecond'] === undefined) return false;
    if (!('expansionBytesWritten' in value) || value['expansionBytesWritten'] === undefined) return false;
    if (!('expansionBytesDeclared' in value) || value['expansionBytesDeclared'] === undefined) return false;
    return true;
}

export function TransferJobDtoFromJSON(json: any): TransferJobDto {
    return TransferJobDtoFromJSONTyped(json, false);
}

export function TransferJobDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferJobDto {
    if (json == null) {
        return json;
    }
    return {
        
        'jobId': json['jobId'],
        'deviceId': json['deviceId'],
        'storageType': TeensyStorageTypeFromJSON(json['storageType']),
        'destinationDirectory': json['destinationDirectory'],
        'state': TransferJobStateFromJSON(json['state']),
        'filesReceived': json['filesReceived'],
        'filesSent': json['filesSent'],
        'filesFailed': json['filesFailed'],
        'bytesSent': json['bytesSent'],
        'totalFiles': json['totalFiles'] === undefined ? undefined : json['totalFiles'] === null ? null : json['totalFiles'],
        'currentFile': json['currentFile'] === undefined ? undefined : json['currentFile'] === null ? null : json['currentFile'],
        'startedUtc': (new Date(json['startedUtc'])),
        'lastActivityUtc': (new Date(json['lastActivityUtc'])),
        'error': json['error'] === undefined ? undefined : json['error'] === null ? null : json['error'],
        'failures': ((json['failures'] as Array<any>).map(TransferFileCompletedFromJSON)),
        'recentCompletions': ((json['recentCompletions'] as Array<any>).map(TransferFileCompletedFromJSON)),
        'bytesPerSecond': json['bytesPerSecond'],
        'filesPerSecond': json['filesPerSecond'],
        'expandingArchive': json['expandingArchive'] === undefined ? undefined : json['expandingArchive'] === null ? null : json['expandingArchive'],
        'expansionBytesWritten': json['expansionBytesWritten'],
        'expansionBytesDeclared': json['expansionBytesDeclared'],
        'expandedFileCount': json['expandedFileCount'] === undefined ? undefined : json['expandedFileCount'] === null ? null : json['expandedFileCount'],
    };
}

export function TransferJobDtoToJSON(json: any): TransferJobDto {
    return TransferJobDtoToJSONTyped(json, false);
}

export function TransferJobDtoToJSONTyped(value?: TransferJobDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jobId': value['jobId'],
        'deviceId': value['deviceId'],
        'storageType': TeensyStorageTypeToJSON(value['storageType']),
        'destinationDirectory': value['destinationDirectory'],
        'state': TransferJobStateToJSON(value['state']),
        'filesReceived': value['filesReceived'],
        'filesSent': value['filesSent'],
        'filesFailed': value['filesFailed'],
        'bytesSent': value['bytesSent'],
        'totalFiles': value['totalFiles'],
        'currentFile': value['currentFile'],
        'startedUtc': value['startedUtc'].toISOString(),
        'lastActivityUtc': value['lastActivityUtc'].toISOString(),
        'error': value['error'],
        'failures': ((value['failures'] as Array<any>).map(TransferFileCompletedToJSON)),
        'recentCompletions': ((value['recentCompletions'] as Array<any>).map(TransferFileCompletedToJSON)),
        'bytesPerSecond': value['bytesPerSecond'],
        'filesPerSecond': value['filesPerSecond'],
        'expandingArchive': value['expandingArchive'],
        'expansionBytesWritten': value['expansionBytesWritten'],
        'expansionBytesDeclared': value['expansionBytesDeclared'],
        'expandedFileCount': value['expandedFileCount'],
    };
}

