/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1.0.0-alpha.8
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-alpha.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransferFileCompleted
 */
export interface TransferFileCompleted {
    /**
     * 
     * @type {string}
     * @memberof TransferFileCompleted
     */
    jobId: string;
    /**
     * 
     * @type {string}
     * @memberof TransferFileCompleted
     */
    relativePath: string;
    /**
     * 
     * @type {string}
     * @memberof TransferFileCompleted
     */
    targetPath: string;
    /**
     * 
     * @type {boolean}
     * @memberof TransferFileCompleted
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof TransferFileCompleted
     */
    error: string | null;
    /**
     * 
     * @type {number}
     * @memberof TransferFileCompleted
     */
    sizeBytes: number;
}

/**
 * Check if a given object implements the TransferFileCompleted interface.
 */
export function instanceOfTransferFileCompleted(value: object): value is TransferFileCompleted {
    if (!('jobId' in value) || value['jobId'] === undefined) return false;
    if (!('relativePath' in value) || value['relativePath'] === undefined) return false;
    if (!('targetPath' in value) || value['targetPath'] === undefined) return false;
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('sizeBytes' in value) || value['sizeBytes'] === undefined) return false;
    return true;
}

export function TransferFileCompletedFromJSON(json: any): TransferFileCompleted {
    return TransferFileCompletedFromJSONTyped(json, false);
}

export function TransferFileCompletedFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferFileCompleted {
    if (json == null) {
        return json;
    }
    return {
        
        'jobId': json['jobId'],
        'relativePath': json['relativePath'],
        'targetPath': json['targetPath'],
        'success': json['success'],
        'error': json['error'],
        'sizeBytes': json['sizeBytes'],
    };
}

export function TransferFileCompletedToJSON(json: any): TransferFileCompleted {
    return TransferFileCompletedToJSONTyped(json, false);
}

export function TransferFileCompletedToJSONTyped(value?: TransferFileCompleted | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jobId': value['jobId'],
        'relativePath': value['relativePath'],
        'targetPath': value['targetPath'],
        'success': value['success'],
        'error': value['error'],
        'sizeBytes': value['sizeBytes'],
    };
}

