/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1.0.0-alpha.8
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-alpha.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TeensyStorageType } from './TeensyStorageType';
import {
    TeensyStorageTypeFromJSON,
    TeensyStorageTypeFromJSONTyped,
    TeensyStorageTypeToJSON,
    TeensyStorageTypeToJSONTyped,
} from './TeensyStorageType';
import type { TransferJobState } from './TransferJobState';
import {
    TransferJobStateFromJSON,
    TransferJobStateFromJSONTyped,
    TransferJobStateToJSON,
    TransferJobStateToJSONTyped,
} from './TransferJobState';
import type { TransferFileCompleted } from './TransferFileCompleted';
import {
    TransferFileCompletedFromJSON,
    TransferFileCompletedFromJSONTyped,
    TransferFileCompletedToJSON,
    TransferFileCompletedToJSONTyped,
} from './TransferFileCompleted';

/**
 * 
 * @export
 * @interface TransferJobDto
 */
export interface TransferJobDto {
    /**
     * 
     * @type {string}
     * @memberof TransferJobDto
     */
    jobId: string;
    /**
     * 
     * @type {string}
     * @memberof TransferJobDto
     */
    deviceId: string;
    /**
     * 
     * @type {TeensyStorageType}
     * @memberof TransferJobDto
     */
    storageType: TeensyStorageType;
    /**
     * 
     * @type {string}
     * @memberof TransferJobDto
     */
    destinationDirectory: string;
    /**
     * 
     * @type {TransferJobState}
     * @memberof TransferJobDto
     */
    state: TransferJobState;
    /**
     * 
     * @type {number}
     * @memberof TransferJobDto
     */
    filesReceived: number;
    /**
     * 
     * @type {number}
     * @memberof TransferJobDto
     */
    filesSent: number;
    /**
     * 
     * @type {number}
     * @memberof TransferJobDto
     */
    filesFailed: number;
    /**
     * 
     * @type {number}
     * @memberof TransferJobDto
     */
    bytesSent: number;
    /**
     * 
     * @type {number}
     * @memberof TransferJobDto
     */
    totalFiles?: number | null;
    /**
     * 
     * @type {string}
     * @memberof TransferJobDto
     */
    currentFile?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof TransferJobDto
     */
    startedUtc: Date;
    /**
     * 
     * @type {Date}
     * @memberof TransferJobDto
     */
    lastActivityUtc: Date;
    /**
     * 
     * @type {string}
     * @memberof TransferJobDto
     */
    error?: string | null;
    /**
     * 
     * @type {Array<TransferFileCompleted>}
     * @memberof TransferJobDto
     */
    failures: Array<TransferFileCompleted>;
}



/**
 * Check if a given object implements the TransferJobDto interface.
 */
export function instanceOfTransferJobDto(value: object): value is TransferJobDto {
    if (!('jobId' in value) || value['jobId'] === undefined) return false;
    if (!('deviceId' in value) || value['deviceId'] === undefined) return false;
    if (!('storageType' in value) || value['storageType'] === undefined) return false;
    if (!('destinationDirectory' in value) || value['destinationDirectory'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('filesReceived' in value) || value['filesReceived'] === undefined) return false;
    if (!('filesSent' in value) || value['filesSent'] === undefined) return false;
    if (!('filesFailed' in value) || value['filesFailed'] === undefined) return false;
    if (!('bytesSent' in value) || value['bytesSent'] === undefined) return false;
    if (!('startedUtc' in value) || value['startedUtc'] === undefined) return false;
    if (!('lastActivityUtc' in value) || value['lastActivityUtc'] === undefined) return false;
    if (!('failures' in value) || value['failures'] === undefined) return false;
    return true;
}

export function TransferJobDtoFromJSON(json: any): TransferJobDto {
    return TransferJobDtoFromJSONTyped(json, false);
}

export function TransferJobDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferJobDto {
    if (json == null) {
        return json;
    }
    return {
        
        'jobId': json['jobId'],
        'deviceId': json['deviceId'],
        'storageType': TeensyStorageTypeFromJSON(json['storageType']),
        'destinationDirectory': json['destinationDirectory'],
        'state': TransferJobStateFromJSON(json['state']),
        'filesReceived': json['filesReceived'],
        'filesSent': json['filesSent'],
        'filesFailed': json['filesFailed'],
        'bytesSent': json['bytesSent'],
        'totalFiles': json['totalFiles'] == null ? undefined : json['totalFiles'],
        'currentFile': json['currentFile'] == null ? undefined : json['currentFile'],
        'startedUtc': (new Date(json['startedUtc'])),
        'lastActivityUtc': (new Date(json['lastActivityUtc'])),
        'error': json['error'] == null ? undefined : json['error'],
        'failures': ((json['failures'] as Array<any>).map(TransferFileCompletedFromJSON)),
    };
}

export function TransferJobDtoToJSON(json: any): TransferJobDto {
    return TransferJobDtoToJSONTyped(json, false);
}

export function TransferJobDtoToJSONTyped(value?: TransferJobDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jobId': value['jobId'],
        'deviceId': value['deviceId'],
        'storageType': TeensyStorageTypeToJSON(value['storageType']),
        'destinationDirectory': value['destinationDirectory'],
        'state': TransferJobStateToJSON(value['state']),
        'filesReceived': value['filesReceived'],
        'filesSent': value['filesSent'],
        'filesFailed': value['filesFailed'],
        'bytesSent': value['bytesSent'],
        'totalFiles': value['totalFiles'],
        'currentFile': value['currentFile'],
        'startedUtc': ((value['startedUtc']).toISOString()),
        'lastActivityUtc': ((value['lastActivityUtc']).toISOString()),
        'error': value['error'],
        'failures': ((value['failures'] as Array<any>).map(TransferFileCompletedToJSON)),
    };
}

