/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1.0.0-alpha.8
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-alpha.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TransferJobState = {
    Created: 'Created',
    Receiving: 'Receiving',
    Sealed: 'Sealed',
    Completed: 'Completed',
    Cancelling: 'Cancelling',
    Cancelled: 'Cancelled',
    Abandoned: 'Abandoned',
    Aborted: 'Aborted'
} as const;
export type TransferJobState = typeof TransferJobState[keyof typeof TransferJobState];


export function instanceOfTransferJobState(value: any): boolean {
    for (const key in TransferJobState) {
        if (Object.prototype.hasOwnProperty.call(TransferJobState, key)) {
            if (TransferJobState[key as keyof typeof TransferJobState] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TransferJobStateFromJSON(json: any): TransferJobState {
    return TransferJobStateFromJSONTyped(json, false);
}

export function TransferJobStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferJobState {
    return json as TransferJobState;
}

export function TransferJobStateToJSON(value?: TransferJobState | null): any {
    return value as any;
}

export function TransferJobStateToJSONTyped(value: any, ignoreDiscriminator: boolean): TransferJobState {
    return value as TransferJobState;
}

