/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1.0.0-alpha.8
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-alpha.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadFileResponse
 */
export interface UploadFileResponse {
    /**
     * 
     * @type {string}
     * @memberof UploadFileResponse
     */
    relativePath: string;
    /**
     * 
     * @type {number}
     * @memberof UploadFileResponse
     */
    sizeBytes: number;
    /**
     * 
     * @type {boolean}
     * @memberof UploadFileResponse
     */
    queued: boolean;
}

/**
 * Check if a given object implements the UploadFileResponse interface.
 */
export function instanceOfUploadFileResponse(value: object): value is UploadFileResponse {
    if (!('relativePath' in value) || value['relativePath'] === undefined) return false;
    if (!('sizeBytes' in value) || value['sizeBytes'] === undefined) return false;
    if (!('queued' in value) || value['queued'] === undefined) return false;
    return true;
}

export function UploadFileResponseFromJSON(json: any): UploadFileResponse {
    return UploadFileResponseFromJSONTyped(json, false);
}

export function UploadFileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadFileResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'relativePath': json['relativePath'],
        'sizeBytes': json['sizeBytes'],
        'queued': json['queued'],
    };
}

export function UploadFileResponseToJSON(json: any): UploadFileResponse {
    return UploadFileResponseToJSONTyped(json, false);
}

export function UploadFileResponseToJSONTyped(value?: UploadFileResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'relativePath': value['relativePath'],
        'sizeBytes': value['sizeBytes'],
        'queued': value['queued'],
    };
}

