/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1.0.0-alpha.8
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-alpha.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const VideoStandard = {
    Unknown: 'Unknown',
    Ntsc: 'NTSC',
    Pal: 'PAL'
} as const;
export type VideoStandard = typeof VideoStandard[keyof typeof VideoStandard];


export function instanceOfVideoStandard(value: any): boolean {
    for (const key in VideoStandard) {
        if (Object.prototype.hasOwnProperty.call(VideoStandard, key)) {
            if (VideoStandard[key as keyof typeof VideoStandard] === value) {
                return true;
            }
        }
    }
    return false;
}

export function VideoStandardFromJSON(json: any): VideoStandard {
    return VideoStandardFromJSONTyped(json, false);
}

export function VideoStandardFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoStandard {
    return json as VideoStandard;
}

export function VideoStandardToJSON(value?: VideoStandard | null): any {
    return value as any;
}

export function VideoStandardToJSONTyped(value: any, ignoreDiscriminator: boolean): VideoStandard {
    return value as VideoStandard;
}

