/* tslint:disable */
/* eslint-disable */
/**
 * TeensyRom.Api | v1.0.0-alpha.1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoSettingsDto
 */
export interface VideoSettingsDto {
    /**
     * 
     * @type {boolean}
     * @memberof VideoSettingsDto
     */
    enableVideo: boolean;
    /**
     * 
     * @type {string}
     * @memberof VideoSettingsDto
     */
    videoDeviceId: string;
}

/**
 * Check if a given object implements the VideoSettingsDto interface.
 */
export function instanceOfVideoSettingsDto(value: object): value is VideoSettingsDto {
    if (!('enableVideo' in value) || value['enableVideo'] === undefined) return false;
    if (!('videoDeviceId' in value) || value['videoDeviceId'] === undefined) return false;
    return true;
}

export function VideoSettingsDtoFromJSON(json: any): VideoSettingsDto {
    return VideoSettingsDtoFromJSONTyped(json, false);
}

export function VideoSettingsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoSettingsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'enableVideo': json['enableVideo'],
        'videoDeviceId': json['videoDeviceId'],
    };
}

export function VideoSettingsDtoToJSON(json: any): VideoSettingsDto {
    return VideoSettingsDtoToJSONTyped(json, false);
}

export function VideoSettingsDtoToJSONTyped(value?: VideoSettingsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enableVideo': value['enableVideo'],
        'videoDeviceId': value['videoDeviceId'],
    };
}

