/* tslint:disable */
/* eslint-disable */
/**
 * Assembly64 API
 * Swagger documentation for Assembly64 API operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: freabe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Backer
 */
export interface Backer {
    /**
     * 
     * @type {string}
     * @memberof Backer
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Backer
     */
    date?: string;
}

/**
 * Check if a given object implements the Backer interface.
 */
export function instanceOfBacker(value: object): value is Backer {
    return true;
}

export function BackerFromJSON(json: any): Backer {
    return BackerFromJSONTyped(json, false);
}

export function BackerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Backer {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'date': json['date'] == null ? undefined : json['date'],
    };
}

export function BackerToJSON(json: any): Backer {
    return BackerToJSONTyped(json, false);
}

export function BackerToJSONTyped(value?: Backer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'date': value['date'],
    };
}

