/* tslint:disable */
/* eslint-disable */
/**
 * Assembly64 API
 * Swagger documentation for Assembly64 API operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: freabe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CategoryMapping
 */
export interface CategoryMapping {
    /**
     * 
     * @type {number}
     * @memberof CategoryMapping
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CategoryMapping
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryMapping
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryMapping
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryMapping
     */
    groupingName?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof CategoryMapping
     */
    availableDownloadAllLevels?: Array<number>;
}

/**
 * Check if a given object implements the CategoryMapping interface.
 */
export function instanceOfCategoryMapping(value: object): value is CategoryMapping {
    return true;
}

export function CategoryMappingFromJSON(json: any): CategoryMapping {
    return CategoryMappingFromJSONTyped(json, false);
}

export function CategoryMappingFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryMapping {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
        'description': json['description'] == null ? undefined : json['description'],
        'groupingName': json['groupingName'] == null ? undefined : json['groupingName'],
        'availableDownloadAllLevels': json['availableDownloadAllLevels'] == null ? undefined : json['availableDownloadAllLevels'],
    };
}

export function CategoryMappingToJSON(json: any): CategoryMapping {
    return CategoryMappingToJSONTyped(json, false);
}

export function CategoryMappingToJSONTyped(value?: CategoryMapping | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'type': value['type'],
        'description': value['description'],
        'groupingName': value['groupingName'],
        'availableDownloadAllLevels': value['availableDownloadAllLevels'],
    };
}

