/* tslint:disable */
/* eslint-disable */
/**
 * Assembly64 API
 * Swagger documentation for Assembly64 API operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: freabe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CollectionChecksumNew
 */
export interface CollectionChecksumNew {
    /**
     * 
     * @type {number}
     * @memberof CollectionChecksumNew
     */
    publicList?: number;
    /**
     * 
     * @type {number}
     * @memberof CollectionChecksumNew
     */
    privateList?: number;
}

/**
 * Check if a given object implements the CollectionChecksumNew interface.
 */
export function instanceOfCollectionChecksumNew(value: object): value is CollectionChecksumNew {
    return true;
}

export function CollectionChecksumNewFromJSON(json: any): CollectionChecksumNew {
    return CollectionChecksumNewFromJSONTyped(json, false);
}

export function CollectionChecksumNewFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionChecksumNew {
    if (json == null) {
        return json;
    }
    return {
        
        'publicList': json['publicList'] == null ? undefined : json['publicList'],
        'privateList': json['privateList'] == null ? undefined : json['privateList'],
    };
}

export function CollectionChecksumNewToJSON(json: any): CollectionChecksumNew {
    return CollectionChecksumNewToJSONTyped(json, false);
}

export function CollectionChecksumNewToJSONTyped(value?: CollectionChecksumNew | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'publicList': value['publicList'],
        'privateList': value['privateList'],
    };
}

