/* tslint:disable */
/* eslint-disable */
/**
 * Assembly64 API
 * Swagger documentation for Assembly64 API operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: freabe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContentCollectionItem } from './ContentCollectionItem';
import {
    ContentCollectionItemFromJSON,
    ContentCollectionItemFromJSONTyped,
    ContentCollectionItemToJSON,
    ContentCollectionItemToJSONTyped,
} from './ContentCollectionItem';
import type { CollectionChecksumNew } from './CollectionChecksumNew';
import {
    CollectionChecksumNewFromJSON,
    CollectionChecksumNewFromJSONTyped,
    CollectionChecksumNewToJSON,
    CollectionChecksumNewToJSONTyped,
} from './CollectionChecksumNew';
import type { ContentCollection } from './ContentCollection';
import {
    ContentCollectionFromJSON,
    ContentCollectionFromJSONTyped,
    ContentCollectionToJSON,
    ContentCollectionToJSONTyped,
} from './ContentCollection';

/**
 * 
 * @export
 * @interface CollectionData
 */
export interface CollectionData {
    /**
     * 
     * @type {string}
     * @memberof CollectionData
     */
    collectionType?: CollectionDataCollectionTypeEnum;
    /**
     * 
     * @type {CollectionChecksumNew}
     * @memberof CollectionData
     */
    checksum?: CollectionChecksumNew;
    /**
     * 
     * @type {Array<ContentCollection>}
     * @memberof CollectionData
     */
    collections?: Array<ContentCollection>;
    /**
     * 
     * @type {Array<ContentCollection>}
     * @memberof CollectionData
     */
    publicCollections?: Array<ContentCollection>;
    /**
     * 
     * @type {Array<ContentCollectionItem>}
     * @memberof CollectionData
     */
    tracks?: Array<ContentCollectionItem>;
    /**
     * 
     * @type {number}
     * @memberof CollectionData
     */
    playlistId?: number;
}


/**
 * @export
 */
export const CollectionDataCollectionTypeEnum = {
    Playlist: 'PLAYLIST',
    UserCollection: 'USER_COLLECTION',
    DjPlayer: 'DJ_PLAYER'
} as const;
export type CollectionDataCollectionTypeEnum = typeof CollectionDataCollectionTypeEnum[keyof typeof CollectionDataCollectionTypeEnum];


/**
 * Check if a given object implements the CollectionData interface.
 */
export function instanceOfCollectionData(value: object): value is CollectionData {
    return true;
}

export function CollectionDataFromJSON(json: any): CollectionData {
    return CollectionDataFromJSONTyped(json, false);
}

export function CollectionDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionData {
    if (json == null) {
        return json;
    }
    return {
        
        'collectionType': json['collectionType'] == null ? undefined : json['collectionType'],
        'checksum': json['checksum'] == null ? undefined : CollectionChecksumNewFromJSON(json['checksum']),
        'collections': json['collections'] == null ? undefined : ((json['collections'] as Array<any>).map(ContentCollectionFromJSON)),
        'publicCollections': json['publicCollections'] == null ? undefined : ((json['publicCollections'] as Array<any>).map(ContentCollectionFromJSON)),
        'tracks': json['tracks'] == null ? undefined : ((json['tracks'] as Array<any>).map(ContentCollectionItemFromJSON)),
        'playlistId': json['playlistId'] == null ? undefined : json['playlistId'],
    };
}

export function CollectionDataToJSON(json: any): CollectionData {
    return CollectionDataToJSONTyped(json, false);
}

export function CollectionDataToJSONTyped(value?: CollectionData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'collectionType': value['collectionType'],
        'checksum': CollectionChecksumNewToJSON(value['checksum']),
        'collections': value['collections'] == null ? undefined : ((value['collections'] as Array<any>).map(ContentCollectionToJSON)),
        'publicCollections': value['publicCollections'] == null ? undefined : ((value['publicCollections'] as Array<any>).map(ContentCollectionToJSON)),
        'tracks': value['tracks'] == null ? undefined : ((value['tracks'] as Array<any>).map(ContentCollectionItemToJSON)),
        'playlistId': value['playlistId'],
    };
}

