/* tslint:disable */
/* eslint-disable */
/**
 * Assembly64 API
 * Swagger documentation for Assembly64 API operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: freabe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompoType
 */
export interface CompoType {
    /**
     * 
     * @type {number}
     * @memberof CompoType
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CompoType
     */
    name?: string;
}

/**
 * Check if a given object implements the CompoType interface.
 */
export function instanceOfCompoType(value: object): value is CompoType {
    return true;
}

export function CompoTypeFromJSON(json: any): CompoType {
    return CompoTypeFromJSONTyped(json, false);
}

export function CompoTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompoType {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function CompoTypeToJSON(json: any): CompoType {
    return CompoTypeToJSONTyped(json, false);
}

export function CompoTypeToJSONTyped(value?: CompoType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

