/* tslint:disable */
/* eslint-disable */
/**
 * Assembly64 API
 * Swagger documentation for Assembly64 API operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: freabe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContentCollectionItem
 */
export interface ContentCollectionItem {
    /**
     * 
     * @type {number}
     * @memberof ContentCollectionItem
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ContentCollectionItem
     */
    itemId?: string;
    /**
     * 
     * @type {number}
     * @memberof ContentCollectionItem
     */
    categoryId?: number;
    /**
     * 
     * @type {string}
     * @memberof ContentCollectionItem
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentCollectionItem
     */
    fileId?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentCollectionItem
     */
    year?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentCollectionItem
     */
    group?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentCollectionItem
     */
    categoryName?: string;
}

/**
 * Check if a given object implements the ContentCollectionItem interface.
 */
export function instanceOfContentCollectionItem(value: object): value is ContentCollectionItem {
    return true;
}

export function ContentCollectionItemFromJSON(json: any): ContentCollectionItem {
    return ContentCollectionItemFromJSONTyped(json, false);
}

export function ContentCollectionItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentCollectionItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'itemId': json['itemId'] == null ? undefined : json['itemId'],
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
        'name': json['name'] == null ? undefined : json['name'],
        'fileId': json['fileId'] == null ? undefined : json['fileId'],
        'year': json['year'] == null ? undefined : json['year'],
        'group': json['group'] == null ? undefined : json['group'],
        'categoryName': json['categoryName'] == null ? undefined : json['categoryName'],
    };
}

export function ContentCollectionItemToJSON(json: any): ContentCollectionItem {
    return ContentCollectionItemToJSONTyped(json, false);
}

export function ContentCollectionItemToJSONTyped(value?: ContentCollectionItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'itemId': value['itemId'],
        'categoryId': value['categoryId'],
        'name': value['name'],
        'fileId': value['fileId'],
        'year': value['year'],
        'group': value['group'],
        'categoryName': value['categoryName'],
    };
}

