/* tslint:disable */
/* eslint-disable */
/**
 * Assembly64 API
 * Swagger documentation for Assembly64 API operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: freabe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContentCollection
 */
export interface ContentCollection {
    /**
     * 
     * @type {string}
     * @memberof ContentCollection
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof ContentCollection
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof ContentCollection
     */
    checksum?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ContentCollection
     */
    publicList?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ContentCollection
     */
    mine?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ContentCollection
     */
    followers?: number;
    /**
     * 
     * @type {string}
     * @memberof ContentCollection
     */
    ownerAlias?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentCollection
     */
    collectionType?: ContentCollectionCollectionTypeEnum;
}


/**
 * @export
 */
export const ContentCollectionCollectionTypeEnum = {
    Playlist: 'PLAYLIST',
    UserCollection: 'USER_COLLECTION',
    DjPlayer: 'DJ_PLAYER'
} as const;
export type ContentCollectionCollectionTypeEnum = typeof ContentCollectionCollectionTypeEnum[keyof typeof ContentCollectionCollectionTypeEnum];


/**
 * Check if a given object implements the ContentCollection interface.
 */
export function instanceOfContentCollection(value: object): value is ContentCollection {
    return true;
}

export function ContentCollectionFromJSON(json: any): ContentCollection {
    return ContentCollectionFromJSONTyped(json, false);
}

export function ContentCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'id': json['id'] == null ? undefined : json['id'],
        'checksum': json['checksum'] == null ? undefined : json['checksum'],
        'publicList': json['publicList'] == null ? undefined : json['publicList'],
        'mine': json['mine'] == null ? undefined : json['mine'],
        'followers': json['followers'] == null ? undefined : json['followers'],
        'ownerAlias': json['ownerAlias'] == null ? undefined : json['ownerAlias'],
        'collectionType': json['collectionType'] == null ? undefined : json['collectionType'],
    };
}

export function ContentCollectionToJSON(json: any): ContentCollection {
    return ContentCollectionToJSONTyped(json, false);
}

export function ContentCollectionToJSONTyped(value?: ContentCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'id': value['id'],
        'checksum': value['checksum'],
        'publicList': value['publicList'],
        'mine': value['mine'],
        'followers': value['followers'],
        'ownerAlias': value['ownerAlias'],
        'collectionType': value['collectionType'],
    };
}

