/* tslint:disable */
/* eslint-disable */
/**
 * Assembly64 API
 * Swagger documentation for Assembly64 API operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: freabe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContentEntryV2 } from './ContentEntryV2';
import {
    ContentEntryV2FromJSON,
    ContentEntryV2FromJSONTyped,
    ContentEntryV2ToJSON,
    ContentEntryV2ToJSONTyped,
} from './ContentEntryV2';

/**
 * 
 * @export
 * @interface ContentEntryContainerV2
 */
export interface ContentEntryContainerV2 {
    /**
     * 
     * @type {Array<ContentEntryV2>}
     * @memberof ContentEntryContainerV2
     */
    contentEntry?: Array<ContentEntryV2>;
}

/**
 * Check if a given object implements the ContentEntryContainerV2 interface.
 */
export function instanceOfContentEntryContainerV2(value: object): value is ContentEntryContainerV2 {
    return true;
}

export function ContentEntryContainerV2FromJSON(json: any): ContentEntryContainerV2 {
    return ContentEntryContainerV2FromJSONTyped(json, false);
}

export function ContentEntryContainerV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentEntryContainerV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'contentEntry': json['contentEntry'] == null ? undefined : ((json['contentEntry'] as Array<any>).map(ContentEntryV2FromJSON)),
    };
}

export function ContentEntryContainerV2ToJSON(json: any): ContentEntryContainerV2 {
    return ContentEntryContainerV2ToJSONTyped(json, false);
}

export function ContentEntryContainerV2ToJSONTyped(value?: ContentEntryContainerV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contentEntry': value['contentEntry'] == null ? undefined : ((value['contentEntry'] as Array<any>).map(ContentEntryV2ToJSON)),
    };
}

