/* tslint:disable */
/* eslint-disable */
/**
 * Assembly64 API
 * Swagger documentation for Assembly64 API operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: freabe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContentEntryV2
 */
export interface ContentEntryV2 {
    /**
     * 
     * @type {string}
     * @memberof ContentEntryV2
     */
    path?: string;
    /**
     * 
     * @type {number}
     * @memberof ContentEntryV2
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof ContentEntryV2
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof ContentEntryV2
     */
    date?: number;
}

/**
 * Check if a given object implements the ContentEntryV2 interface.
 */
export function instanceOfContentEntryV2(value: object): value is ContentEntryV2 {
    return true;
}

export function ContentEntryV2FromJSON(json: any): ContentEntryV2 {
    return ContentEntryV2FromJSONTyped(json, false);
}

export function ContentEntryV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentEntryV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'] == null ? undefined : json['path'],
        'id': json['id'] == null ? undefined : json['id'],
        'size': json['size'] == null ? undefined : json['size'],
        'date': json['date'] == null ? undefined : json['date'],
    };
}

export function ContentEntryV2ToJSON(json: any): ContentEntryV2 {
    return ContentEntryV2ToJSONTyped(json, false);
}

export function ContentEntryV2ToJSONTyped(value?: ContentEntryV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': value['path'],
        'id': value['id'],
        'size': value['size'],
        'date': value['date'],
    };
}

