/* tslint:disable */
/* eslint-disable */
/**
 * Assembly64 API
 * Swagger documentation for Assembly64 API operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: freabe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContentItem
 */
export interface ContentItem {
    /**
     * 
     * @type {string}
     * @memberof ContentItem
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentItem
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof ContentItem
     */
    category?: number;
    /**
     * 
     * @type {number}
     * @memberof ContentItem
     */
    siteCategory?: number;
    /**
     * 
     * @type {number}
     * @memberof ContentItem
     */
    siteRating?: number;
    /**
     * 
     * @type {string}
     * @memberof ContentItem
     */
    group?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentItem
     */
    handle?: string;
    /**
     * 
     * @type {number}
     * @memberof ContentItem
     */
    year?: number;
    /**
     * 
     * @type {string}
     * @memberof ContentItem
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentItem
     */
    event?: string;
    /**
     * 
     * @type {number}
     * @memberof ContentItem
     */
    rating?: number;
    /**
     * 
     * @type {string}
     * @memberof ContentItem
     */
    updated?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentItem
     */
    released?: string;
    /**
     * 
     * @type {number}
     * @memberof ContentItem
     */
    place?: number;
    /**
     * 
     * @type {number}
     * @memberof ContentItem
     */
    compo?: number;
}

/**
 * Check if a given object implements the ContentItem interface.
 */
export function instanceOfContentItem(value: object): value is ContentItem {
    return true;
}

export function ContentItemFromJSON(json: any): ContentItem {
    return ContentItemFromJSONTyped(json, false);
}

export function ContentItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentItem {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'id': json['id'] == null ? undefined : json['id'],
        'category': json['category'] == null ? undefined : json['category'],
        'siteCategory': json['siteCategory'] == null ? undefined : json['siteCategory'],
        'siteRating': json['siteRating'] == null ? undefined : json['siteRating'],
        'group': json['group'] == null ? undefined : json['group'],
        'handle': json['handle'] == null ? undefined : json['handle'],
        'year': json['year'] == null ? undefined : json['year'],
        'country': json['country'] == null ? undefined : json['country'],
        'event': json['event'] == null ? undefined : json['event'],
        'rating': json['rating'] == null ? undefined : json['rating'],
        'updated': json['updated'] == null ? undefined : json['updated'],
        'released': json['released'] == null ? undefined : json['released'],
        'place': json['place'] == null ? undefined : json['place'],
        'compo': json['compo'] == null ? undefined : json['compo'],
    };
}

export function ContentItemToJSON(json: any): ContentItem {
    return ContentItemToJSONTyped(json, false);
}

export function ContentItemToJSONTyped(value?: ContentItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'id': value['id'],
        'category': value['category'],
        'siteCategory': value['siteCategory'],
        'siteRating': value['siteRating'],
        'group': value['group'],
        'handle': value['handle'],
        'year': value['year'],
        'country': value['country'],
        'event': value['event'],
        'rating': value['rating'],
        'updated': value['updated'],
        'released': value['released'],
        'place': value['place'],
        'compo': value['compo'],
    };
}

