/* tslint:disable */
/* eslint-disable */
/**
 * Assembly64 API
 * Swagger documentation for Assembly64 API operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: freabe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FlipInfoEntry
 */
export interface FlipInfoEntry {
    /**
     * 
     * @type {string}
     * @memberof FlipInfoEntry
     */
    diskName?: string;
    /**
     * 
     * @type {number}
     * @memberof FlipInfoEntry
     */
    length?: number;
    /**
     * 
     * @type {string}
     * @memberof FlipInfoEntry
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof FlipInfoEntry
     */
    category?: number;
    /**
     * 
     * @type {string}
     * @memberof FlipInfoEntry
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof FlipInfoEntry
     */
    group?: string;
    /**
     * 
     * @type {string}
     * @memberof FlipInfoEntry
     */
    event?: string;
    /**
     * 
     * @type {number}
     * @memberof FlipInfoEntry
     */
    year?: number;
}

/**
 * Check if a given object implements the FlipInfoEntry interface.
 */
export function instanceOfFlipInfoEntry(value: object): value is FlipInfoEntry {
    return true;
}

export function FlipInfoEntryFromJSON(json: any): FlipInfoEntry {
    return FlipInfoEntryFromJSONTyped(json, false);
}

export function FlipInfoEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): FlipInfoEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'diskName': json['diskName'] == null ? undefined : json['diskName'],
        'length': json['length'] == null ? undefined : json['length'],
        'id': json['id'] == null ? undefined : json['id'],
        'category': json['category'] == null ? undefined : json['category'],
        'name': json['name'] == null ? undefined : json['name'],
        'group': json['group'] == null ? undefined : json['group'],
        'event': json['event'] == null ? undefined : json['event'],
        'year': json['year'] == null ? undefined : json['year'],
    };
}

export function FlipInfoEntryToJSON(json: any): FlipInfoEntry {
    return FlipInfoEntryToJSONTyped(json, false);
}

export function FlipInfoEntryToJSONTyped(value?: FlipInfoEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'diskName': value['diskName'],
        'length': value['length'],
        'id': value['id'],
        'category': value['category'],
        'name': value['name'],
        'group': value['group'],
        'event': value['event'],
        'year': value['year'],
    };
}

