/* tslint:disable */
/* eslint-disable */
/**
 * Assembly64 API
 * Swagger documentation for Assembly64 API operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: freabe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TargetAndPath } from './TargetAndPath';
import {
    TargetAndPathFromJSON,
    TargetAndPathFromJSONTyped,
    TargetAndPathToJSON,
    TargetAndPathToJSONTyped,
} from './TargetAndPath';

/**
 * 
 * @export
 * @interface Metadata
 */
export interface Metadata {
    /**
     * 
     * @type {string}
     * @memberof Metadata
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Metadata
     */
    group?: string;
    /**
     * 
     * @type {string}
     * @memberof Metadata
     */
    handle?: string;
    /**
     * 
     * @type {string}
     * @memberof Metadata
     */
    releaseDate?: string;
    /**
     * 
     * @type {string}
     * @memberof Metadata
     */
    event?: string;
    /**
     * 
     * @type {string}
     * @memberof Metadata
     */
    eventType?: string;
    /**
     * 
     * @type {string}
     * @memberof Metadata
     */
    rating?: string;
    /**
     * 
     * @type {string}
     * @memberof Metadata
     */
    place?: string;
    /**
     * 
     * @type {string}
     * @memberof Metadata
     */
    url?: string;
    /**
     * 
     * @type {Set<TargetAndPath>}
     * @memberof Metadata
     */
    images?: Set<TargetAndPath>;
    /**
     * 
     * @type {string}
     * @memberof Metadata
     */
    siteImage?: string;
}

/**
 * Check if a given object implements the Metadata interface.
 */
export function instanceOfMetadata(value: object): value is Metadata {
    return true;
}

export function MetadataFromJSON(json: any): Metadata {
    return MetadataFromJSONTyped(json, false);
}

export function MetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): Metadata {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'group': json['group'] == null ? undefined : json['group'],
        'handle': json['handle'] == null ? undefined : json['handle'],
        'releaseDate': json['releaseDate'] == null ? undefined : json['releaseDate'],
        'event': json['event'] == null ? undefined : json['event'],
        'eventType': json['eventType'] == null ? undefined : json['eventType'],
        'rating': json['rating'] == null ? undefined : json['rating'],
        'place': json['place'] == null ? undefined : json['place'],
        'url': json['url'] == null ? undefined : json['url'],
        'images': json['images'] == null ? undefined : (new Set((json['images'] as Array<any>).map(TargetAndPathFromJSON))),
        'siteImage': json['siteImage'] == null ? undefined : json['siteImage'],
    };
}

export function MetadataToJSON(json: any): Metadata {
    return MetadataToJSONTyped(json, false);
}

export function MetadataToJSONTyped(value?: Metadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'group': value['group'],
        'handle': value['handle'],
        'releaseDate': value['releaseDate'],
        'event': value['event'],
        'eventType': value['eventType'],
        'rating': value['rating'],
        'place': value['place'],
        'url': value['url'],
        'images': value['images'] == null ? undefined : (Array.from(value['images'] as Set<any>).map(TargetAndPathToJSON)),
        'siteImage': value['siteImage'],
    };
}

