/* tslint:disable */
/* eslint-disable */
/**
 * Assembly64 API
 * Swagger documentation for Assembly64 API operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: freabe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PresetEntry
 */
export interface PresetEntry {
    /**
     * 
     * @type {number}
     * @memberof PresetEntry
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PresetEntry
     */
    aqlKey?: string;
    /**
     * 
     * @type {string}
     * @memberof PresetEntry
     */
    name?: string;
}

/**
 * Check if a given object implements the PresetEntry interface.
 */
export function instanceOfPresetEntry(value: object): value is PresetEntry {
    return true;
}

export function PresetEntryFromJSON(json: any): PresetEntry {
    return PresetEntryFromJSONTyped(json, false);
}

export function PresetEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PresetEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'aqlKey': json['aqlKey'] == null ? undefined : json['aqlKey'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function PresetEntryToJSON(json: any): PresetEntry {
    return PresetEntryToJSONTyped(json, false);
}

export function PresetEntryToJSONTyped(value?: PresetEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'aqlKey': value['aqlKey'],
        'name': value['name'],
    };
}

