/* tslint:disable */
/* eslint-disable */
/**
 * Assembly64 API
 * Swagger documentation for Assembly64 API operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: freabe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PresetEntry } from './PresetEntry';
import {
    PresetEntryFromJSON,
    PresetEntryFromJSONTyped,
    PresetEntryToJSON,
    PresetEntryToJSONTyped,
} from './PresetEntry';

/**
 * 
 * @export
 * @interface Preset
 */
export interface Preset {
    /**
     * 
     * @type {string}
     * @memberof Preset
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof Preset
     */
    description?: string;
    /**
     * 
     * @type {Array<PresetEntry>}
     * @memberof Preset
     */
    values?: Array<PresetEntry>;
}

/**
 * Check if a given object implements the Preset interface.
 */
export function instanceOfPreset(value: object): value is Preset {
    return true;
}

export function PresetFromJSON(json: any): Preset {
    return PresetFromJSONTyped(json, false);
}

export function PresetFromJSONTyped(json: any, ignoreDiscriminator: boolean): Preset {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'description': json['description'] == null ? undefined : json['description'],
        'values': json['values'] == null ? undefined : ((json['values'] as Array<any>).map(PresetEntryFromJSON)),
    };
}

export function PresetToJSON(json: any): Preset {
    return PresetToJSONTyped(json, false);
}

export function PresetToJSONTyped(value?: Preset | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'description': value['description'],
        'values': value['values'] == null ? undefined : ((value['values'] as Array<any>).map(PresetEntryToJSON)),
    };
}

