/* tslint:disable */
/* eslint-disable */
/**
 * Assembly64 API
 * Swagger documentation for Assembly64 API operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: freabe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Settings
 */
export interface Settings {
    /**
     * 
     * @type {boolean}
     * @memberof Settings
     */
    anonymous?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Settings
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Settings
     */
    country?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Settings
     */
    broadcastLogin?: boolean;
}

/**
 * Check if a given object implements the Settings interface.
 */
export function instanceOfSettings(value: object): value is Settings {
    return true;
}

export function SettingsFromJSON(json: any): Settings {
    return SettingsFromJSONTyped(json, false);
}

export function SettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Settings {
    if (json == null) {
        return json;
    }
    return {
        
        'anonymous': json['anonymous'] == null ? undefined : json['anonymous'],
        'name': json['name'] == null ? undefined : json['name'],
        'country': json['country'] == null ? undefined : json['country'],
        'broadcastLogin': json['broadcastLogin'] == null ? undefined : json['broadcastLogin'],
    };
}

export function SettingsToJSON(json: any): Settings {
    return SettingsToJSONTyped(json, false);
}

export function SettingsToJSONTyped(value?: Settings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'anonymous': value['anonymous'],
        'name': value['name'],
        'country': value['country'],
        'broadcastLogin': value['broadcastLogin'],
    };
}

