/* tslint:disable */
/* eslint-disable */
/**
 * Assembly64 API
 * Swagger documentation for Assembly64 API operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: freabe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TargetAndPath
 */
export interface TargetAndPath {
    /**
     * 
     * @type {string}
     * @memberof TargetAndPath
     */
    path?: string;
    /**
     * 
     * @type {string}
     * @memberof TargetAndPath
     */
    target?: string;
}

/**
 * Check if a given object implements the TargetAndPath interface.
 */
export function instanceOfTargetAndPath(value: object): value is TargetAndPath {
    return true;
}

export function TargetAndPathFromJSON(json: any): TargetAndPath {
    return TargetAndPathFromJSONTyped(json, false);
}

export function TargetAndPathFromJSONTyped(json: any, ignoreDiscriminator: boolean): TargetAndPath {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'] == null ? undefined : json['path'],
        'target': json['target'] == null ? undefined : json['target'],
    };
}

export function TargetAndPathToJSON(json: any): TargetAndPath {
    return TargetAndPathToJSONTyped(json, false);
}

export function TargetAndPathToJSONTyped(value?: TargetAndPath | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': value['path'],
        'target': value['target'],
    };
}

