/* tslint:disable */
/* eslint-disable */
/**
 * Assembly64 API
 * Swagger documentation for Assembly64 API operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: freabe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserLite
 */
export interface UserLite {
    /**
     * 
     * @type {string}
     * @memberof UserLite
     */
    token?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserLite
     */
    premium?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserLite
     */
    anonymous?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserLite
     */
    features?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UserLite
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UserLite
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UserLite
     */
    country?: string;
    /**
     * 
     * @type {number}
     * @memberof UserLite
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof UserLite
     */
    clientId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserLite
     */
    heroModeActive?: boolean;
}

/**
 * Check if a given object implements the UserLite interface.
 */
export function instanceOfUserLite(value: object): value is UserLite {
    return true;
}

export function UserLiteFromJSON(json: any): UserLite {
    return UserLiteFromJSONTyped(json, false);
}

export function UserLiteFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserLite {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'] == null ? undefined : json['token'],
        'premium': json['premium'] == null ? undefined : json['premium'],
        'anonymous': json['anonymous'] == null ? undefined : json['anonymous'],
        'features': json['features'] == null ? undefined : json['features'],
        'email': json['email'] == null ? undefined : json['email'],
        'name': json['name'] == null ? undefined : json['name'],
        'country': json['country'] == null ? undefined : json['country'],
        'id': json['id'] == null ? undefined : json['id'],
        'clientId': json['clientId'] == null ? undefined : json['clientId'],
        'heroModeActive': json['heroModeActive'] == null ? undefined : json['heroModeActive'],
    };
}

export function UserLiteToJSON(json: any): UserLite {
    return UserLiteToJSONTyped(json, false);
}

export function UserLiteToJSONTyped(value?: UserLite | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'premium': value['premium'],
        'anonymous': value['anonymous'],
        'features': value['features'],
        'email': value['email'],
        'name': value['name'],
        'country': value['country'],
        'id': value['id'],
        'clientId': value['clientId'],
        'heroModeActive': value['heroModeActive'],
    };
}

