/* tslint:disable */
/* eslint-disable */
/**
 * Assembly64 API
 * Swagger documentation for Assembly64 API operations.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: freabe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserSystemNotification
 */
export interface UserSystemNotification {
    /**
     * 
     * @type {string}
     * @memberof UserSystemNotification
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof UserSystemNotification
     */
    platform?: string;
    /**
     * 
     * @type {string}
     * @memberof UserSystemNotification
     */
    message?: string;
}

/**
 * Check if a given object implements the UserSystemNotification interface.
 */
export function instanceOfUserSystemNotification(value: object): value is UserSystemNotification {
    return true;
}

export function UserSystemNotificationFromJSON(json: any): UserSystemNotification {
    return UserSystemNotificationFromJSONTyped(json, false);
}

export function UserSystemNotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSystemNotification {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'platform': json['platform'] == null ? undefined : json['platform'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function UserSystemNotificationToJSON(json: any): UserSystemNotification {
    return UserSystemNotificationToJSONTyped(json, false);
}

export function UserSystemNotificationToJSONTyped(value?: UserSystemNotification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'platform': value['platform'],
        'message': value['message'],
    };
}

