import { Injectable, inject } from '@angular/core';
import { ALERT_SERVICE } from '@teensyrom-nx/domain';
import { logError } from '@teensyrom-nx/utils';

export const DJ_DATABASE_NAME = 'teensyrom-dj';
export const DJ_DATABASE_VERSION = 1;
export const TUNES_STORE = 'tunes';
export const DECK_BINDINGS_STORE = 'deck-bindings';

/**
 * The one IndexedDB database for everything DJ. Opens lazily on first use, memoises the open
 * across the whole application, and turns every failure mode — private browsing, quota, a
 * corrupt database, `indexedDB` missing entirely — into a `null` database rather than a thrown
 * error. Nothing above this class ever sees `IDBDatabase`, `IDBRequest`, or a transaction: `get`,
 * `put`, `getAll`, and `update` are the only surface, and `update` is the only way to do a
 * read-modify-write, always inside one `readwrite` transaction so two writers to the same row
 * (e.g. `putBytes` and `putIndex`) never race a `get` against another writer's `put`.
 */
@Injectable({ providedIn: 'root' })
export class DjDatabase {
  private readonly alertService = inject(ALERT_SERVICE);
  private openPromise: Promise<IDBDatabase | null> | null = null;

  open(): Promise<IDBDatabase | null> {
    if (!this.openPromise) {
      this.openPromise = this.openDatabase();
    }
    return this.openPromise;
  }

  async get<T>(store: string, key: IDBValidKey): Promise<T | undefined> {
    const db = await this.open();
    if (!db) return undefined;
    return this.request<T | undefined>(db, store, 'readonly', (os) => os.get(key));
  }

  async put<T>(store: string, value: T): Promise<void> {
    const db = await this.open();
    if (!db) return;
    await this.request<IDBValidKey>(db, store, 'readwrite', (os) => os.put(value));
  }

  async getAll<T>(store: string): Promise<T[]> {
    const db = await this.open();
    if (!db) return [];
    return this.request<T[]>(db, store, 'readonly', (os) => os.getAll());
  }

  update<T>(store: string, key: IDBValidKey, mutate: (row: T | undefined) => T): Promise<void> {
    return this.open().then((db) => {
      if (!db) return;
      return new Promise<void>((resolve, reject) => {
        const tx = db.transaction(store, 'readwrite');
        const objectStore = tx.objectStore(store);
        const getRequest = objectStore.get(key);

        getRequest.onsuccess = () => {
          let next: T;
          try {
            next = mutate(getRequest.result as T | undefined);
          } catch (error) {
            reject(error);
            tx.abort();
            return;
          }
          objectStore.put(next);
        };
        getRequest.onerror = () => reject(getRequest.error);
        tx.oncomplete = () => resolve();
        tx.onerror = () => reject(tx.error);
        tx.onabort = () => reject(tx.error ?? new Error('DjDatabase.update transaction aborted'));
      });
    });
  }

  private openDatabase(): Promise<IDBDatabase | null> {
    if (typeof indexedDB === 'undefined') {
      return Promise.resolve(this.fail(new Error('indexedDB is unavailable in this environment')));
    }

    return new Promise<IDBDatabase | null>((resolve) => {
      let request: IDBOpenDBRequest;
      try {
        request = indexedDB.open(DJ_DATABASE_NAME, DJ_DATABASE_VERSION);
      } catch (error) {
        resolve(this.fail(error));
        return;
      }

      /*
       * Version policy: DJ_DATABASE_VERSION describes the *shape* of the two stores, never the
       * content of a record in them. `tunes` holds bytes and index records that are entirely
       * derived from a scan of the cartridge's own file — on a future incompatible bump it may be
       * dropped and recreated from scratch, since nothing in it cannot be regenerated by scanning
       * again. `deck-bindings` holds a user's own choice of which MIDI port a slot is bound to —
       * a preference, not a derived cache — so it is migrated forward on a bump and
       * never dropped. A record's own `formatVersion` (see `TuneIndexRecord`) describes a scan's
       * content and never bumps this database: content versioning and schema versioning are
       * deliberately separate axes, and conflating them would force a full re-scan of every tune
       * whenever a single detector's weights change.
       */
      request.onupgradeneeded = () => {
        const db = request.result;
        if (!db.objectStoreNames.contains(TUNES_STORE)) {
          db.createObjectStore(TUNES_STORE, { keyPath: 'sidHash' });
        }
        if (!db.objectStoreNames.contains(DECK_BINDINGS_STORE)) {
          db.createObjectStore(DECK_BINDINGS_STORE, { keyPath: 'slot' });
        }
      };

      request.onsuccess = () => {
        const db = request.result;
        db.onversionchange = () => db.close();
        resolve(db);
      };

      request.onerror = () => resolve(this.fail(request.error));
    });
  }

  private request<T>(
    db: IDBDatabase,
    store: string,
    mode: IDBTransactionMode,
    run: (objectStore: IDBObjectStore) => IDBRequest<T>
  ): Promise<T> {
    return new Promise<T>((resolve, reject) => {
      const tx = db.transaction(store, mode);
      const objectStore = tx.objectStore(store);
      const req = run(objectStore);
      // Resolved from `tx.oncomplete`, not `req.onsuccess` — a request can succeed and still have
      // its transaction abort before committing (quota exceeded, a disk error, another request in
      // the same transaction failing), same reasoning as `update()` below. The request's own result
      // is captured here and handed out once the transaction actually commits.
      let result: T;
      req.onsuccess = () => {
        result = req.result;
      };
      req.onerror = () => reject(req.error);
      tx.oncomplete = () => resolve(result);
      tx.onerror = () => reject(tx.error);
      tx.onabort = () => reject(tx.error ?? new Error('DjDatabase.request transaction aborted'));
    });
  }

  private fail(error: unknown): null {
    logError('DjDatabase.open failed — DJ storage is unavailable', error);
    this.alertService.warning(
      'DJ storage is unavailable — nothing will be remembered across a refresh.'
    );
    return null;
  }
}
